## Dataset inmuebles publicados de Mercado Libre

In [32]:
import pandas as pd

In [33]:
df_original =  pd.read_csv("Base_ML.csv")

df_original

,Número de Publicación,Fecha,Tipo de Inmueble,Uso,Título,Operación,Condición,Precio,Precio en USD,Divisa,...,Superficie Construida,Unidad Superficie,Superficie total en m²,Antiguedad,Ubicación,Municipio,Estado,año-mes,trimestre,Cuenta
0,4684947390,2026-01-19,Comercial,Comercial,Renta Local Comercial 1 Ambiente Residencias I...,Renta,Usado,12000.0,NaN,MXN,...,250.0,m²,283.0,20,Normal; 322; Residencias Imperiales; Mexicali;...,Mexicali,Baja California,2026-01,2026Q1,1
1,2829377483,2026-03-30,Comercial,Comercial,Oficina En Renta En Pinos Del Norte; Merida Yu...,Renta,Nuevo,12000.0,NaN,MXN,...,1.0,m²,1.0,0,Pinos Norte II; Mérida; Yucatán,Mérida,Yucatán,2026-03,2026Q1,1
2,4682387082,2026-01-19,Departamento,Vivienda,Departamento De Una Recámara En Planta Baja; C...,Renta,Usado,12000.0,NaN,MXN,...,65.0,m²,80.0,40,Reembolsos 83; Postal; Ciudad De México; Posta...,Benito Juárez,Ciudad de México,2026-01,2026Q1,1
3,5196128934,2026-04-16,Departamento,Vivienda,Departamento En Renta !! Residencial Mapimi *s...,Renta,Usado,12000.0,NaN,MXN,...,56.0,m²,56.0,5,Mapimí 65; Valle Gómez; Ciudad De México; Vall...,Cuauhtémoc,Ciudad de México,2026-04,2026Q2,1
4,5196093914,2026-04-16,Departamento,Vivienda,* Depto En Renta * Cerca Metrobus La Viga,Renta,Usado,12000.0,NaN,MXN,...,65.0,m²,65.0,12,Calzada De La Viga 777; Santiago Norte; Iztaca...,Iztacalco,Ciudad de México,2026-04,2026Q2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134582,5257430348,2026-04-28,Casa,Vivienda,Residencia De Lujo En Jardines Del Pedregal,Venta,Usado,20071000.0,NaN,MXN,...,522.0,m²,750.0,NaN,Jardines Del Pedregal; Mexico City; Jardines D...,Alvaro Obregón,Ciudad de México,2026-04,2026Q2,1
134583,2745019269,2026-02-17,Departamento,Vivienda,Departamento En Venta En Lomas De Tecamachalco,Venta,Usado,20100000.0,NaN,MXN,...,308.0,m²,308.0,NaN,Departamento En Venta O Renta Lomas De Tecamac...,Naucalpan,México,2026-02,2026Q1,1
134584,5220683406,2026-04-21,Comercial,Comercial,Local Comercial En Renta En Norte Del Ciudad M...,Venta,Nuevo,20101890.0,NaN,MXN,...,295.0,m²,295.0,0,Altabrisa; Mérida; Yucatán,Mérida,Yucatán,2026-04,2026Q2,1
134585,2832631759,2026-03-31,Comercial,Comercial,Local Comercial En Renta En Norte Del Ciudad M...,Venta,Nuevo,20101890.0,NaN,MXN,...,295.0,m²,295.0,0,Altabrisa; Mérida; Yucatán,Mérida,Yucatán,2026-03,2026Q1,1
134586,5285287198,2026-05-04,Comercial,Comercial,Local Comercial En Renta En Norte Del Ciudad M...,Venta,Nuevo,20101890.0,NaN,MXN,...,295.0,m²,295.0,0,Altabrisa; Mérida; Yucatán,Mérida,Yucatán,2026-05,2026Q2,1

# EDA: Análisis de Datos Exploratorio

In [34]:
df_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134587 entries, 0 to 134586
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Número de Publicación   134587 non-null  int64
 1   Fecha                   134587 non-null  object
 2   Tipo de Inmueble        134587 non-null  object
 3   Uso                     134587 non-null  object
 4   Título                  134587 non-null  object
 5   Operación               134587 non-null  object
 6   Condición               134587 non-null  object
 7   Precio                  134587 non-null  float64
 8   Precio en USD           3190 non-null    float64
 9   Divisa                  134587 non-null  object
 10  Precio en MXN           134587 non-null  float64
 11  Superficie Total        134587 non-null  float64
 12  Superficie Construida   132341 non-null  float64
 13  Unidad Superficie       134587 non-null  object
 14  Superficie total en m²  134587 non-null  float64
 15  Antiguedad              122935 non-null  object
 16  Ubicación               134226 non-null  object
 17  Municipio               134226 non-null  object
 18  Estado                  134226 non-null  object
 19  año-mes                 134587 non-null  object
 20  trimestre               134587 non-null  object
 21  Cuenta                  134587 non-null  int64
dtypes: float64(6), int64(2), object(14)
memory usage: 22.6+ MB

In [35]:
df_original.shape

(134587, 22)

In [36]:
df_original.info

<bound method DataFrame.info of         Número de Publicación       Fecha Tipo de Inmueble        Uso  \
0                  4684947390  2026-01-19        Comercial  Comercial
1                  2829377483  2026-03-30        Comercial  Comercial
2                  4682387082  2026-01-19     Departamento   Vivienda
3                  5196128934  2026-04-16     Departamento   Vivienda
4                  5196093914  2026-04-16     Departamento   Vivienda
...                       ...         ...              ...        ...
134582             5257430348  2026-04-28             Casa   Vivienda
134583             2745019269  2026-02-17     Departamento   Vivienda
134584             5220683406  2026-04-21        Comercial  Comercial
134585             2832631759  2026-03-31        Comercial  Comercial
134586             5285287198  2026-05-04        Comercial  Comercial

                                                   Título Operación Condición  \
0       Renta Local Comercial 1 Ambiente Residencias I...     Renta     Usado
1       Oficina En Renta En Pinos Del Norte; Merida Yu...     Renta     Nuevo
2       Departamento De Una Recámara En Planta Baja; C...     Renta     Usado
3       Departamento En Renta !! Residencial Mapimi *s...     Renta     Usado
4              * Depto En Renta  * Cerca Metrobus La Viga     Renta     Usado
...                                                   ...       ...       ...
134582        Residencia De Lujo En Jardines Del Pedregal     Venta     Usado
134583     Departamento En Venta En Lomas De Tecamachalco     Venta     Usado
134584  Local Comercial En Renta En Norte Del Ciudad M...     Venta     Nuevo
134585  Local Comercial En Renta En Norte Del Ciudad M...     Venta     Nuevo
134586  Local Comercial En Renta En Norte Del Ciudad M...     Venta     Nuevo

            Precio  Precio en USD Divisa  ...  Superficie Construida  \
0          12000.0            NaN    MXN  ...                  250.0
1          12000.0            NaN    MXN  ...                    1.0
2          12000.0            NaN    MXN  ...                   65.0
3          12000.0            NaN    MXN  ...                   56.0
4          12000.0            NaN    MXN  ...                   65.0
...            ...            ...    ...  ...                    ...
134582  20071000.0            NaN    MXN  ...                  522.0
134583  20100000.0            NaN    MXN  ...                  308.0
134584  20101890.0            NaN    MXN  ...                  295.0
134585  20101890.0            NaN    MXN  ...                  295.0
134586  20101890.0            NaN    MXN  ...                  295.0

        Unidad Superficie  Superficie total en m² Antiguedad  \
0                      m²                   283.0         20
1                      m²                     1.0          0
2                      m²                    80.0         40
3                      m²                    56.0          5
4                      m²                    65.0         12
...                   ...                     ...        ...
134582                 m²                   750.0        NaN
134583                 m²                   308.0        NaN
134584                 m²                   295.0          0
134585                 m²                   295.0          0
134586                 m²                   295.0          0

                                                Ubicación       Municipio  \
0       Normal; 322; Residencias Imperiales; Mexicali;...        Mexicali
1                         Pinos Norte II; Mérida; Yucatán          Mérida
2       Reembolsos 83; Postal; Ciudad De México; Posta...   Benito Juárez
3       Mapimí 65; Valle Gómez; Ciudad De México; Vall...      Cuauhtémoc
4       Calzada De La Viga 777; Santiago Norte; Iztaca...       Iztacalco
...                                                   ...             ...
134582  Jardines Del Pedregal; Mexico City; Jardines D...  Alvaro Obregón
134583  Departamento En Venta O Renta Lomas De Tecamac...       Naucalpan
134584                         Altabrisa; Mérida; Yucatán          Mérida
134585                         Altabrisa; Mérida; Yucatán          Mérida
134586                         Altabrisa; Mérida; Yucatán          Mérida

                  Estado  año-mes trimestre Cuenta
0        Baja California  2026-01    2026Q1      1
1                Yucatán  2026-03    2026Q1      1
2       Ciudad de México  2026-01    2026Q1      1
3       Ciudad de México  2026-04    2026Q2      1
4       Ciudad de México  2026-04    2026Q2      1
...                  ...      ...       ...    ...
134582  Ciudad de México  2026-04    2026Q2      1
134583            México  2026-02    2026Q1      1
134584           Yucatán  2026-04    2026Q2      1
134585           Yucatán  2026-03    2026Q1      1
134586           Yucatán  2026-05    2026Q2      1

[134587 rows x 22 columns]>

In [37]:
df_original.head()

## Cuenta: sirve para hacer conteos dentro de la tabla**

,Número de Publicación,Fecha,Tipo de Inmueble,Uso,Título,Operación,Condición,Precio,Precio en USD,Divisa,...,Superficie Construida,Unidad Superficie,Superficie total en m²,Antiguedad,Ubicación,Municipio,Estado,año-mes,trimestre,Cuenta
0,4684947390,2026-01-19,Comercial,Comercial,Renta Local Comercial 1 Ambiente Residencias I...,Renta,Usado,12000.0,NaN,MXN,...,250.0,m²,283.0,20,Normal; 322; Residencias Imperiales; Mexicali;...,Mexicali,Baja California,2026-01,2026Q1,1
1,2829377483,2026-03-30,Comercial,Comercial,Oficina En Renta En Pinos Del Norte; Merida Yu...,Renta,Nuevo,12000.0,NaN,MXN,...,1.0,m²,1.0,0,Pinos Norte II; Mérida; Yucatán,Mérida,Yucatán,2026-03,2026Q1,1
2,4682387082,2026-01-19,Departamento,Vivienda,Departamento De Una Recámara En Planta Baja; C...,Renta,Usado,12000.0,NaN,MXN,...,65.0,m²,80.0,40,Reembolsos 83; Postal; Ciudad De México; Posta...,Benito Juárez,Ciudad de México,2026-01,2026Q1,1
3,5196128934,2026-04-16,Departamento,Vivienda,Departamento En Renta !! Residencial Mapimi *s...,Renta,Usado,12000.0,NaN,MXN,...,56.0,m²,56.0,5,Mapimí 65; Valle Gómez; Ciudad De México; Vall...,Cuauhtémoc,Ciudad de México,2026-04,2026Q2,1
4,5196093914,2026-04-16,Departamento,Vivienda,* Depto En Renta * Cerca Metrobus La Viga,Renta,Usado,12000.0,NaN,MXN,...,65.0,m²,65.0,12,Calzada De La Viga 777; Santiago Norte; Iztaca...,Iztacalco,Ciudad de México,2026-04,2026Q2,1

In [38]:
df_original.tail(5)

,Número de Publicación,Fecha,Tipo de Inmueble,Uso,Título,Operación,Condición,Precio,Precio en USD,Divisa,...,Superficie Construida,Unidad Superficie,Superficie total en m²,Antiguedad,Ubicación,Municipio,Estado,año-mes,trimestre,Cuenta
134582,5257430348,2026-04-28,Casa,Vivienda,Residencia De Lujo En Jardines Del Pedregal,Venta,Usado,20071000.0,NaN,MXN,...,522.0,m²,750.0,NaN,Jardines Del Pedregal; Mexico City; Jardines D...,Alvaro Obregón,Ciudad de México,2026-04,2026Q2,1
134583,2745019269,2026-02-17,Departamento,Vivienda,Departamento En Venta En Lomas De Tecamachalco,Venta,Usado,20100000.0,NaN,MXN,...,308.0,m²,308.0,NaN,Departamento En Venta O Renta Lomas De Tecamac...,Naucalpan,México,2026-02,2026Q1,1
134584,5220683406,2026-04-21,Comercial,Comercial,Local Comercial En Renta En Norte Del Ciudad M...,Venta,Nuevo,20101890.0,NaN,MXN,...,295.0,m²,295.0,0,Altabrisa; Mérida; Yucatán,Mérida,Yucatán,2026-04,2026Q2,1
134585,2832631759,2026-03-31,Comercial,Comercial,Local Comercial En Renta En Norte Del Ciudad M...,Venta,Nuevo,20101890.0,NaN,MXN,...,295.0,m²,295.0,0,Altabrisa; Mérida; Yucatán,Mérida,Yucatán,2026-03,2026Q1,1
134586,5285287198,2026-05-04,Comercial,Comercial,Local Comercial En Renta En Norte Del Ciudad M...,Venta,Nuevo,20101890.0,NaN,MXN,...,295.0,m²,295.0,0,Altabrisa; Mérida; Yucatán,Mérida,Yucatán,2026-05,2026Q2,1

In [39]:
df_original.describe()

,Número de Publicación,Precio,Precio en USD,Precio en MXN,Superficie Total,Superficie Construida,Superficie total en m²,Cuenta
count,1.345870e+05,1.345870e+05,3.190000e+03,1.345870e+05,134587.000000,132341.000000,134587.000000,134587.0
mean,3.927602e+09,3.987873e+06,2.360846e+05,4.080366e+06,317.332184,245.310760,317.332184,1.0
std,1.079197e+09,4.623363e+06,2.959387e+05,4.654982e+06,1700.118219,2487.253071,1700.118219,0.0
min,2.423448e+09,7.000000e+02,7.000000e+02,1.200000e+04,1.000000,0.000000,1.000000,1.0
25%,2.760781e+09,7.000000e+04,1.080000e+04,8.000000e+04,90.000000,78.000000,90.000000,1.0
50%,4.640919e+09,2.620000e+06,9.500000e+04,2.760000e+06,150.000000,145.000000,150.000000,1.0
75%,4.948082e+09,6.000000e+06,3.686500e+05,6.200000e+06,270.000000,260.000000,270.000000,1.0
max,5.310790e+09,2.010189e+07,1.162389e+06,2.010189e+07,140501.000000,530261.000000,140501.000000,1.0

In [40]:
df_original.describe(include = "all")

,Número de Publicación,Fecha,Tipo de Inmueble,Uso,Título,Operación,Condición,Precio,Precio en USD,Divisa,...,Superficie Construida,Unidad Superficie,Superficie total en m²,Antiguedad,Ubicación,Municipio,Estado,año-mes,trimestre,Cuenta
count,1.345870e+05,134587,134587,134587,134587,134587,134587,1.345870e+05,3.190000e+03,134587,...,132341.000000,134587,134587.000000,122935,134226,134226,134226,134587,134587,134587.0
unique,NaN,79,3,2,94323,2,2,NaN,NaN,2,...,NaN,1,NaN,226,65520,708,32,5,2,NaN
top,NaN,2026-02-12,Casa,Vivienda,Departamento En Venta En Polanco,Venta,Usado,NaN,NaN,MXN,...,NaN,m²,NaN,0,Polanco; Miguel Hidalgo; Distrito Federal,Miguel Hidalgo,Ciudad de México,2026-02,2026Q1,NaN
freq,NaN,3062,60980,113695,172,90879,78206,NaN,NaN,131397,...,NaN,134587,NaN,54746,1795,10150,44572,35710,101201,NaN
mean,3.927602e+09,NaN,NaN,NaN,NaN,NaN,NaN,3.987873e+06,2.360846e+05,NaN,...,245.310760,NaN,317.332184,NaN,NaN,NaN,NaN,NaN,NaN,1.0
std,1.079197e+09,NaN,NaN,NaN,NaN,NaN,NaN,4.623363e+06,2.959387e+05,NaN,...,2487.253071,NaN,1700.118219,NaN,NaN,NaN,NaN,NaN,NaN,0.0
min,2.423448e+09,NaN,NaN,NaN,NaN,NaN,NaN,7.000000e+02,7.000000e+02,NaN,...,0.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.0
25%,2.760781e+09,NaN,NaN,NaN,NaN,NaN,NaN,7.000000e+04,1.080000e+04,NaN,...,78.000000,NaN,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.0
50%,4.640919e+09,NaN,NaN,NaN,NaN,NaN,NaN,2.620000e+06,9.500000e+04,NaN,...,145.000000,NaN,150.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.0
75%,4.948082e+09,NaN,NaN,NaN,NaN,NaN,NaN,6.000000e+06,3.686500e+05,NaN,...,260.000000,NaN,270.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.0
max,5.310790e+09,NaN,NaN,NaN,NaN,NaN,NaN,2.010189e+07,1.162389e+06,NaN,...,530261.000000,NaN,140501.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [41]:
df =  df_original.copy()

In [42]:
## Conversion de fecha

df["Fecha"] = pd.to_datetime(df["Fecha"])

df.info

<bound method DataFrame.info of         Número de Publicación      Fecha Tipo de Inmueble        Uso  \
0                  4684947390 2026-01-19        Comercial  Comercial
1                  2829377483 2026-03-30        Comercial  Comercial
2                  4682387082 2026-01-19     Departamento   Vivienda
3                  5196128934 2026-04-16     Departamento   Vivienda
4                  5196093914 2026-04-16     Departamento   Vivienda
...                       ...        ...              ...        ...
134582             5257430348 2026-04-28             Casa   Vivienda
134583             2745019269 2026-02-17     Departamento   Vivienda
134584             5220683406 2026-04-21        Comercial  Comercial
134585             2832631759 2026-03-31        Comercial  Comercial
134586             5285287198 2026-05-04        Comercial  Comercial

                                                   Título Operación Condición  \
0       Renta Local Comercial 1 Ambiente Residencias I...     Renta     Usado
1       Oficina En Renta En Pinos Del Norte; Merida Yu...     Renta     Nuevo
2       Departamento De Una Recámara En Planta Baja; C...     Renta     Usado
3       Departamento En Renta !! Residencial Mapimi *s...     Renta     Usado
4              * Depto En Renta  * Cerca Metrobus La Viga     Renta     Usado
...                                                   ...       ...       ...
134582        Residencia De Lujo En Jardines Del Pedregal     Venta     Usado
134583     Departamento En Venta En Lomas De Tecamachalco     Venta     Usado
134584  Local Comercial En Renta En Norte Del Ciudad M...     Venta     Nuevo
134585  Local Comercial En Renta En Norte Del Ciudad M...     Venta     Nuevo
134586  Local Comercial En Renta En Norte Del Ciudad M...     Venta     Nuevo

            Precio  Precio en USD Divisa  ...  Superficie Construida  \
0          12000.0            NaN    MXN  ...                  250.0
1          12000.0            NaN    MXN  ...                    1.0
2          12000.0            NaN    MXN  ...                   65.0
3          12000.0            NaN    MXN  ...                   56.0
4          12000.0            NaN    MXN  ...                   65.0
...            ...            ...    ...  ...                    ...
134582  20071000.0            NaN    MXN  ...                  522.0
134583  20100000.0            NaN    MXN  ...                  308.0
134584  20101890.0            NaN    MXN  ...                  295.0
134585  20101890.0            NaN    MXN  ...                  295.0
134586  20101890.0            NaN    MXN  ...                  295.0

        Unidad Superficie  Superficie total en m² Antiguedad  \
0                      m²                   283.0         20
1                      m²                     1.0          0
2                      m²                    80.0         40
3                      m²                    56.0          5
4                      m²                    65.0         12
...                   ...                     ...        ...
134582                 m²                   750.0        NaN
134583                 m²                   308.0        NaN
134584                 m²                   295.0          0
134585                 m²                   295.0          0
134586                 m²                   295.0          0

                                                Ubicación       Municipio  \
0       Normal; 322; Residencias Imperiales; Mexicali;...        Mexicali
1                         Pinos Norte II; Mérida; Yucatán          Mérida
2       Reembolsos 83; Postal; Ciudad De México; Posta...   Benito Juárez
3       Mapimí 65; Valle Gómez; Ciudad De México; Vall...      Cuauhtémoc
4       Calzada De La Viga 777; Santiago Norte; Iztaca...       Iztacalco
...                                                   ...             ...
134582  Jardines Del Pedregal; Mexico City; Jardines D...  Alvaro Obregón
134583  Departamento En Venta O Renta Lomas De Tecamac...       Naucalpan
134584                         Altabrisa; Mérida; Yucatán          Mérida
134585                         Altabrisa; Mérida; Yucatán          Mérida
134586                         Altabrisa; Mérida; Yucatán          Mérida

                  Estado  año-mes trimestre Cuenta
0        Baja California  2026-01    2026Q1      1
1                Yucatán  2026-03    2026Q1      1
2       Ciudad de México  2026-01    2026Q1      1
3       Ciudad de México  2026-04    2026Q2      1
4       Ciudad de México  2026-04    2026Q2      1
...                  ...      ...       ...    ...
134582  Ciudad de México  2026-04    2026Q2      1
134583            México  2026-02    2026Q1      1
134584           Yucatán  2026-04    2026Q2      1
134585           Yucatán  2026-03    2026Q1      1
134586           Yucatán  2026-05    2026Q2      1

[134587 rows x 22 columns]>

In [43]:
df["Fecha"].min()

Timestamp('2026-01-02 00:00:00')

In [44]:
df["Fecha"].max()

Timestamp('2026-05-08 00:00:00')

## Exploración de datos null

In [45]:
#df.isna().sum().sort_values(normalize = True)

In [46]:
df.isna().mean().sort_values(ascending = False) * 100

Precio en USD             97.629786
Antiguedad                 8.657597
Superficie Construida      1.668809
Estado                     0.268228
Municipio                  0.268228
Ubicación                  0.268228
Número de Publicación      0.000000
trimestre                  0.000000
año-mes                    0.000000
Superficie total en m²     0.000000
Unidad Superficie          0.000000
Superficie Total           0.000000
Fecha                      0.000000
Precio en MXN              0.000000
Divisa                     0.000000
Precio                     0.000000
Condición                  0.000000
Operación                  0.000000
Título                     0.000000
Uso                        0.000000
Tipo de Inmueble           0.000000
Cuenta                     0.000000
dtype: float64

## Imputación de valores

In [47]:
filtro =   df["Antiguedad"].isna()
df[filtro]

## ¿Sería necesario imputar la columna antigüedad?
## Validar si hay correlacioón con otras columnas

,Número de Publicación,Fecha,Tipo de Inmueble,Uso,Título,Operación,Condición,Precio,Precio en USD,Divisa,...,Superficie Construida,Unidad Superficie,Superficie total en m²,Antiguedad,Ubicación,Municipio,Estado,año-mes,trimestre,Cuenta
10,5195267710,2026-04-16,Departamento,Vivienda,Ubicacion Privilegiada; Cerca De Centros De Tr...,Renta,Usado,12000.0,NaN,MXN,...,50.0,m²,50.0,NaN,Lago Ammer 1 - 300; Pensil Nte.; Ciudad De Méx...,Miguel Hidalgo,Ciudad de México,2026-04,2026Q2,1
16,2716385691,2026-01-27,Departamento,Vivienda,Departamento En Renta En Banjidal Iztapalapa,Renta,Usado,12000.0,NaN,MXN,...,60.0,m²,60.0,NaN,Banjidal; Mexico City; Banjidal; Iztapalapa; D...,Iztapalapa,Ciudad de México,2026-01,2026Q1,1
30,5177451608,2026-04-13,Casa,Vivienda,Rento Casa En Fraccionamiento Privado En Fortí...,Renta,Usado,12000.0,NaN,MXN,...,120.0,m²,105.0,NaN,Fortín De Las Flores; Fortín De Las Flores; Fo...,Fortín,Veracruz,2026-04,2026Q2,1
31,2894614497,2026-04-27,Casa,Vivienda,Casa En Renta Cuautla Morelos; Colonia Otilio ...,Renta,Usado,12000.0,NaN,MXN,...,184.0,m²,104.0,NaN,Cuautla Morelos; Centro; Cuautla; Otilio Monta...,Cuautla,Morelos,2026-04,2026Q2,1
32,2894766331,2026-04-27,Departamento,Vivienda,Renta Departamento Mezquite Zakia,Renta,Nuevo,12000.0,NaN,MXN,...,89.0,m²,89.0,NaN,Trupillo 201; El Marqués; Querétaro,El Marqués,Querétaro,2026-04,2026Q2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134550,2745440543,2026-02-18,Comercial,Comercial,Edificio De Oficinas En Venta Con En Av. Const...,Venta,Usado,20000000.0,NaN,MXN,...,691.0,m²,488.0,NaN,Hacienda De San Ildefonso 1; Mansiones Del Val...,Querétaro,Querétaro,2026-02,2026Q1,1
134568,5186503988,2026-04-14,Casa,Vivienda,Casa En Venta En Jilotepec En Estado De México,Venta,Usado,20000000.0,NaN,MXN,...,287.0,m²,11008.0,NaN,Vialidad Privada 1 - 300; Las Huertas; Jilotep...,Jilotepec,México,2026-04,2026Q2,1
134570,5200925802,2026-04-16,Comercial,Comercial,Edificio Comercial - Habitacional En Venta En ...,Venta,Nuevo,20000000.0,NaN,MXN,...,795.0,m²,795.0,NaN,NaN,NaN,NaN,2026-04,2026Q2,1
134582,5257430348,2026-04-28,Casa,Vivienda,Residencia De Lujo En Jardines Del Pedregal,Venta,Usado,20071000.0,NaN,MXN,...,522.0,m²,750.0,NaN,Jardines Del Pedregal; Mexico City; Jardines D...,Alvaro Obregón,Ciudad de México,2026-04,2026Q2,1
134583,2745019269,2026-02-17,Departamento,Vivienda,Departamento En Venta En Lomas De Tecamachalco,Venta,Usado,20100000.0,NaN,MXN,...,308.0,m²,308.0,NaN,Departamento En Venta O Renta Lomas De Tecamac...,Naucalpan,México,2026-02,2026Q1,1

## Analisis de datos: Univariado

- Identificar los diferentes tipos de inmuebles

In [48]:
df["Tipo de Inmueble"].value_counts()

Tipo de Inmueble
Casa            60980
Departamento    52715
Comercial       20892
Name: count, dtype: int64

- Los diferentes tipos de uso

In [49]:
df["Uso"].value_counts()

Uso
Vivienda     113695
Comercial     20892
Name: count, dtype: int64

In [51]:
df["Operación"].value_counts()

Operación
Venta    90879
Renta    43708
Name: count, dtype: int64

In [52]:
df["Condición"].value_counts()

Condición
Usado    78206
Nuevo    56381
Name: count, dtype: int64

In [53]:
df["Precio"].mean()

3987873.069657545