In [1]:
import pandas as pd

In [ ]:
estudiantes = pd.DataFrame({
    "id_estudiante": [1, 2, 3, 4, 5], # Llave primaria : valor único (PK: Primary Key)
    "nombre": ["Ana", "Luis", "Marta", "Carlos", "Sofía"],
    "grupo": ["A", "A", "B", "B", "C"]
})

estudiantes

   id_estudiante  nombre grupo
0              1     Ana     A
1              2    Luis     A
2              3   Marta     B
3              4  Carlos     B
4              5   Sofía     C

In [ ]:
calificaciones = pd.DataFrame({
    "id_estudiante": [1, 2, 3, 6],  # Llave foránea (Foreign Key:  FK)
    "id_curso": [101, 101, 102, 103],  # llave primaria (PK)
    "calificacion": [9.5, 8.0, 10.0, 7.5]
})

calificaciones

   id_estudiante  id_curso  calificacion
0              1       101           9.5
1              2       101           8.0
2              3       102          10.0
3              6       103           7.5

In [ ]:
cursos = pd.DataFrame({
    "id_curso": [101, 102, 103, 104], # Primary key
    "curso": ["Python", "Pandas", "Bases de datos", "Estadística"],
    "profesor": ["Dr. Gómez", "Mtra. Ruiz", "Dr. Pérez", "Mtra. Torres"]
})

cursos

   id_curso           curso      profesor
0       101          Python     Dr. Gómez
1       102          Pandas    Mtra. Ruiz
2       103  Bases de datos     Dr. Pérez
3       104     Estadística  Mtra. Torres

# Uso de merge

-- how : left, right, inner, outer

In [5]:
## Dataframe izquierdo: esrtudiantes
## Dataframe derecho calificaciones

# Left: Se mantienen todas las filas del dataframe izquierdo
estudiantes.merge(
    calificaciones,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "left"
)

   id_estudiante  nombre grupo  id_curso  calificacion
0              1     Ana     A     101.0           9.5
1              2    Luis     A     101.0           8.0
2              3   Marta     B     102.0          10.0
3              4  Carlos     B       NaN           NaN
4              5   Sofía     C       NaN           NaN

In [14]:
calificaciones.merge(
    estudiantes,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "left"
)

   id_estudiante  id_curso  calificacion nombre grupo
0              1       101           9.5    Ana     A
1              2       101           8.0   Luis     A
2              3       102          10.0  Marta     B
3              6       103           7.5    NaN   NaN

In [ ]:
# Right: Mantienen todas las filas del dataframe derecho
estudiantes.merge(
    calificaciones,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "right"
)

   id_estudiante nombre grupo  id_curso  calificacion
0              1    Ana     A       101           9.5
1              2   Luis     A       101           8.0
2              3  Marta     B       102          10.0
3              6    NaN   NaN       103           7.5

In [13]:
calificaciones.merge(
    estudiantes,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "inner"
)

   id_estudiante  id_curso  calificacion nombre grupo
0              1       101           9.5    Ana     A
1              2       101           8.0   Luis     A
2              3       102          10.0  Marta     B

In [7]:
estudiantes

   id_estudiante  nombre grupo
0              1     Ana     A
1              2    Luis     A
2              3   Marta     B
3              4  Carlos     B
4              5   Sofía     C

In [8]:
calificaciones

   id_estudiante  id_curso  calificacion
0              1       101           9.5
1              2       101           8.0
2              3       102          10.0
3              6       103           7.5

In [9]:
# Inner: Conserva las filas o registros que tengan coincidencia en ambos dataframes o tabla

estudiantes.merge(
    calificaciones,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "inner"
)

   id_estudiante nombre grupo  id_curso  calificacion
0              1    Ana     A       101           9.5
1              2   Luis     A       101           8.0
2              3  Marta     B       102          10.0

In [12]:
calificaciones.merge(
    estudiantes,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "inner"
)

   id_estudiante  id_curso  calificacion nombre grupo
0              1       101           9.5    Ana     A
1              2       101           8.0   Luis     A
2              3       102          10.0  Marta     B

In [10]:
# Outer: Conserva las filas de ambas tablas (dataframes): Tanto los de la izquierda como de la derecha
estudiantes.merge(
    calificaciones,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "outer"
)

   id_estudiante  nombre grupo  id_curso  calificacion
0              1     Ana     A     101.0           9.5
1              2    Luis     A     101.0           8.0
2              3   Marta     B     102.0          10.0
3              4  Carlos     B       NaN           NaN
4              5   Sofía     C       NaN           NaN
5              6     NaN   NaN     103.0           7.5

In [11]:
calificaciones.merge(
    estudiantes,
    on = "id_estudiante",
    how = "outer"
)

   id_estudiante  id_curso  calificacion  nombre grupo
0              1     101.0           9.5     Ana     A
1              2     101.0           8.0    Luis     A
2              3     102.0          10.0   Marta     B
3              4       NaN           NaN  Carlos     B
4              5       NaN           NaN   Sofía     C
5              6     103.0           7.5     NaN   NaN

## Union de 3 tablas

In [15]:
cursos

   id_curso           curso      profesor
0       101          Python     Dr. Gómez
1       102          Pandas    Mtra. Ruiz
2       103  Bases de datos     Dr. Pérez
3       104     Estadística  Mtra. Torres

In [16]:
df_estudiantes_calif = estudiantes.merge(
    calificaciones,
    on = "id_estudiante", # Cuál es la columna que existe en ambos dataframe,
    how = "left"
)
df_estudiantes_calif

   id_estudiante  nombre grupo  id_curso  calificacion
0              1     Ana     A     101.0           9.5
1              2    Luis     A     101.0           8.0
2              3   Marta     B     102.0          10.0
3              4  Carlos     B       NaN           NaN
4              5   Sofía     C       NaN           NaN

In [17]:
df_estudiantes_cursos =  df_estudiantes_calif.merge(
    cursos,
    on = "id_curso",
    how = "left"
)
df_estudiantes_cursos

   id_estudiante  nombre grupo  id_curso  calificacion   curso    profesor
0              1     Ana     A     101.0           9.5  Python   Dr. Gómez
1              2    Luis     A     101.0           8.0  Python   Dr. Gómez
2              3   Marta     B     102.0          10.0  Pandas  Mtra. Ruiz
3              4  Carlos     B       NaN           NaN     NaN         NaN
4              5   Sofía     C       NaN           NaN     NaN         NaN

In [18]:
cursos

   id_curso           curso      profesor
0       101          Python     Dr. Gómez
1       102          Pandas    Mtra. Ruiz
2       103  Bases de datos     Dr. Pérez
3       104     Estadística  Mtra. Torres

In [19]:
df_estudiantes_cursos =  df_estudiantes_calif.merge(
    cursos,
    on = "id_curso",
    how = "right"
)
df_estudiantes_cursos

,id_estudiante,nombre,grupo,id_curso,calificacion,curso,profesor
0,1.0,Ana,A,101.0,9.5,Python,Dr. Gómez
1,2.0,Luis,A,101.0,8.0,Python,Dr. Gómez
2,3.0,Marta,B,102.0,10.0,Pandas,Mtra. Ruiz
3,NaN,NaN,NaN,103.0,NaN,Bases de datos,Dr. Pérez
4,NaN,NaN,NaN,104.0,NaN,Estadística,Mtra. Torres

In [20]:
df_estudiantes_cursos =  df_estudiantes_calif.merge(
    cursos,
    on = "id_curso",
    how = "inner"
)
df_estudiantes_cursos

   id_estudiante nombre grupo  id_curso  calificacion   curso    profesor
0              1    Ana     A     101.0           9.5  Python   Dr. Gómez
1              2   Luis     A     101.0           8.0  Python   Dr. Gómez
2              3  Marta     B     102.0          10.0  Pandas  Mtra. Ruiz

In [ ]:
df_estudiantes_cursos =  df_estudiantes_calif.merge(
    cursos,
    on = "id_curso",
    how = "outer"
)
df_estudiantes_cursos 

## DF1 = id_estudiante --> cambiar el nombre
## DF2 = id_e

,id_estudiante,nombre,grupo,id_curso,calificacion,curso,profesor
0,1.0,Ana,A,101.0,9.5,Python,Dr. Gómez
1,2.0,Luis,A,101.0,8.0,Python,Dr. Gómez
2,3.0,Marta,B,102.0,10.0,Pandas,Mtra. Ruiz
3,NaN,NaN,NaN,103.0,NaN,Bases de datos,Dr. Pérez
4,NaN,NaN,NaN,104.0,NaN,Estadística,Mtra. Torres
5,4.0,Carlos,B,NaN,NaN,NaN,NaN
6,5.0,Sofía,C,NaN,NaN,NaN,NaN

In [23]:
## Dataframes con nombres de columnas diferentes

becas = pd.DataFrame({
    "matricula": [1, 3, 5],
    "tipo_beca": ["Académica", "Deportiva", "Cultural"]
})

becas

   matricula  tipo_beca
0          1  Académica
1          3  Deportiva
2          5   Cultural

In [24]:
estudiantes_becas = estudiantes.merge(
    becas,
    left_on="id_estudiante",
    right_on="matricula",
    how="left"
)

estudiantes_becas

   id_estudiante  nombre grupo  matricula  tipo_beca
0              1     Ana     A        1.0  Académica
1              2    Luis     A        NaN        NaN
2              3   Marta     B        3.0  Deportiva
3              4  Carlos     B        NaN        NaN
4              5   Sofía     C        5.0   Cultural

## JOIN

- Permite unir tablas o dataframes, pero utilizando el índice de este

In [26]:
# Indicamos explícitamente que una columna debe de ser el índice del dataframe
estudiantes_inidice = estudiantes.set_index("id_estudiante") # Se ocuparía la llave primaria
calificaciones_indice = calificaciones.set_index("id_estudiante")

estudiantes_inidice

               nombre grupo
id_estudiante
1                 Ana     A
2                Luis     A
3               Marta     B
4              Carlos     B
5               Sofía     C

In [28]:
calificaciones_indice

               id_curso  calificacion
id_estudiante
1                   101           9.5
2                   101           8.0
3                   102          10.0
6                   103           7.5

In [31]:
union_join = estudiantes_inidice.join(
    calificaciones_indice,
    how = "left"
)

union_join

               nombre grupo  id_curso  calificacion
id_estudiante
1                 Ana     A     101.0           9.5
2                Luis     A     101.0           8.0
3               Marta     B     102.0          10.0
4              Carlos     B       NaN           NaN
5               Sofía     C       NaN           NaN

In [32]:
union_join = estudiantes_inidice.join(
    calificaciones_indice,
    how = "right"
)

union_join

              nombre grupo  id_curso  calificacion
id_estudiante
1                Ana     A       101           9.5
2               Luis     A       101           8.0
3              Marta     B       102          10.0
6                NaN   NaN       103           7.5

In [33]:
union_join = estudiantes_inidice.join(
    calificaciones_indice,
    how = "inner"
)

union_join

              nombre grupo  id_curso  calificacion
id_estudiante
1                Ana     A       101           9.5
2               Luis     A       101           8.0
3              Marta     B       102          10.0

In [34]:
union_join = estudiantes_inidice.join(
    calificaciones_indice,
    how = "outer"
)

union_join

               nombre grupo  id_curso  calificacion
id_estudiante
1                 Ana     A     101.0           9.5
2                Luis     A     101.0           8.0
3               Marta     B     102.0          10.0
4              Carlos     B       NaN           NaN
5               Sofía     C       NaN           NaN
6                 NaN   NaN     103.0           7.5

## Concat

In [35]:
grupo_a = pd.DataFrame({
    "id_estudiante": [1, 2],
    "nombre": ["Ana", "Luis"],
    "grupo": ["A", "A"]
})

grupo_b = pd.DataFrame({
    "id_estudiante": [3, 4],
    "nombre": ["Marta", "Carlos"],
    "grupo": ["B", "B"]
})

In [36]:
grupo_a

   id_estudiante nombre grupo
0              1    Ana     A
1              2   Luis     A

In [37]:
grupo_b

   id_estudiante  nombre grupo
0              3   Marta     B
1              4  Carlos     B

In [ ]:
estudiantes_todos =  pd.concat(
    [grupo_a, grupo_b],
    axis = 0  # Unión a partir de columnas, colocar un dataframe abajo de otro

)

estudiantes_todos

   id_estudiante  nombre grupo
0              1     Ana     A
1              2    Luis     A
0              3   Marta     B
1              4  Carlos     B

In [ ]:
estudiantes_todos =  pd.concat(
    [grupo_a, grupo_b],
    axis = 1  # Unión a partir de filas, une el segundo dataframe  a la derecha del primero

)

estudiantes_todos

   id_estudiante nombre grupo  id_estudiante  nombre grupo
0              1    Ana     A              3   Marta     B
1              2   Luis     A              4  Carlos     B

Une la tabla `estudiantes` con la tabla `calificaciones` para obtener una tabla donde aparezcan todos los estudiantes, aun que no tengan calificación. 

-- how =  left

Obtén únicamente los estudiantes que sí tienen calificación registrada, evitando los nan de la tabla de estudiantes.

-- how = inner

Ejercicio: Crea un dataframe 

- Nombre del estudiante.
- Grupo.
- Calificación.
- Nombre del curso.
- Profesor.

In [46]:
df = estudiantes.merge(
        calificaciones,
        on = "id_estudiante",
        how = "outer").merge(cursos,
        on = "id_curso",
        how = "outer")

df

,id_estudiante,nombre,grupo,id_curso,calificacion,curso,profesor
0,1.0,Ana,A,101.0,9.5,Python,Dr. Gómez
1,2.0,Luis,A,101.0,8.0,Python,Dr. Gómez
2,3.0,Marta,B,102.0,10.0,Pandas,Mtra. Ruiz
3,6.0,NaN,NaN,103.0,7.5,Bases de datos,Dr. Pérez
4,NaN,NaN,NaN,104.0,NaN,Estadística,Mtra. Torres
5,4.0,Carlos,B,NaN,NaN,NaN,NaN
6,5.0,Sofía,C,NaN,NaN,NaN,NaN

In [47]:
df[["nombre","grupo","calificacion","curso","profesor"] ]

   nombre grupo  calificacion           curso      profesor
0     Ana     A           9.5          Python     Dr. Gómez
1    Luis     A           8.0          Python     Dr. Gómez
2   Marta     B          10.0          Pandas    Mtra. Ruiz
3     NaN   NaN           7.5  Bases de datos     Dr. Pérez
4     NaN   NaN           NaN     Estadística  Mtra. Torres
5  Carlos     B           NaN             NaN           NaN
6   Sofía     C           NaN             NaN           NaN