## Regex

#nombre_df.str.contains --> Bool 
#nombre_df.str.extract ---> str

In [94]:
import pandas as pd
import numpy as np

In [95]:
clientes = pd.DataFrame({
    "id_cliente": [1, 2, 3, 4, 5, 6, 7, 8],
    "nombre": [" Ana López ", "Luis Pérez", "Marta Gómez", "Carlos Díaz", "Sofía Ruiz", "Pedro Torres", "Laura Sánchez", "Miguel Herrera"],
    "correo": [
        "ana.lopez@gmail.com",
        "luis_perez@hotmail.com",
        "marta@empresa.mx",
         np.nan,
        "sofia.ruiz@yahoo.com",
        "pedro.torres@gmail",
        "laura.sanchez@outlook.com",
        "miguel#correo.com"
    ],
    "telefono": [
        "55-1234-5678",
        "222 987 6543",
        "(999)1234567",
        "sin telefono",
        "81-5555-8888",
        "+52 55 1111 2222",
        "443.222.9988",
        "12345"
    ],
    "codigo_cliente": ["CLI-001", "CLI-245", "USR-100", "CLI-ABC", "CLI-999", "VIP-777", "CLI-045", "USR-XYZ"],
    "comentario": [
        "Cliente frecuente desde  2022 | 2025",
        "Debe actualizar correo",
        "Compra mensual - VIP",
        "Teléfono pendiente",
        "Cliente nuevo 2024",
        "Registrado el 15/03/2023",
        "Requiere seguimiento en 2025",
        "Sin información adicional"
    ]
})

In [96]:
clientes

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional

In [97]:
filtro = clientes["comentario"].str.contains("frecuente")
filtro

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: comentario, dtype: bool

In [98]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025

In [99]:
filtro = clientes["correo"].str.contains("gmail", na = False)
filtro

0     True
1    False
2    False
3    False
4    False
5     True
6    False
7    False
Name: correo, dtype: bool

In [100]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023

In [101]:
# |
filtro = clientes["correo"].str.contains("gmail|hotmail", na = False)
filtro

0     True
1     True
2    False
3    False
4    False
5     True
6    False
7    False
Name: correo, dtype: bool

In [102]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023

In [103]:
filtro =  clientes["comentario"].str.contains("\|")
filtro

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: comentario, dtype: bool

In [104]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025

In [105]:
#Se empezar con una subcadena especial
filtro = clientes["codigo_cliente"].str.contains("^CLI")
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025

In [106]:
#Terminar con una subcadena $

In [107]:
filtro = clientes["codigo_cliente"].str.contains("45$")
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025

In [108]:
filtro =  clientes["telefono"].str.contains(r"\d")
filtro

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7     True
Name: telefono, dtype: bool

In [109]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional

In [110]:
filtro =  clientes["telefono"].str.contains(r"\d{10}") #10 dígitos consecutivos
clientes[filtro]

Empty DataFrame
Columns: [id_cliente, nombre, correo, telefono, codigo_cliente, comentario]
Index: []

In [111]:
clientes["telefono_formato"] = clientes["telefono"].str.replace("-","").str.replace(" ","").str.replace("+","")
clientes

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025,443.222.9988
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345

In [112]:
filtro =  clientes["telefono_formato"].str.contains(r"\d{10}") #al menos 10 dígitos consecutivos >=10
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222

In [113]:
#Empieze con Cliente y terminé con 2025 en la columna comentario
filtro = clientes["comentario"].str.contains(r"^Cliente")
df1 = clientes[filtro]
df1
#filtro

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888

In [114]:

filtro2 = df1["comentario"].str.contains(r"2025$")
filtro2

0     True
4    False
Name: comentario, dtype: bool

In [115]:
df1[filtro2]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678

In [116]:
#filtro =  clientes["comentario"].str.contains(r"^Cliente(\w)*2025$") --- Buscar patron para que valide ambas condiciones
#filtro

In [117]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888

 - [aeiou]
 - [A-Z]
 - [0-9]
 - [A-Z]{3}

# Encontrar cógigos von 3 letras mayusculas, seguido de un guiónn y que contenta 3 caracteres alfanúmericos

In [118]:
filtro =  clientes["codigo_cliente"].str.contains(r"[A-Z]{3}-[A-Z0-9]")
filtro
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025,443.222.9988
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345

In [119]:
## Solo aquellos que contienen CLI

In [120]:
filtro =  clientes["codigo_cliente"].str.contains(r"CLI-[A-Z0-9]{3}")
filtro

0     True
1     True
2    False
3     True
4     True
5    False
6     True
7    False
Name: codigo_cliente, dtype: bool

In [121]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025,443.222.9988

In [122]:
filtro =  clientes["codigo_cliente"].str.contains(r"^USR")
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345

In [123]:
## Empiecen con USR y TERMINEN CON 3 digitos
filtro =  clientes["codigo_cliente"].str.contains(r"^USR-[0-9]{3}$")
filtro
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567

In [124]:
##Empiece con cliente y termine con 2025
filtro =  clientes["comentario"].str.contains(r"^Cliente.*2025$") #Cualquier carácter en medio, sin la cantidad de vecees que se repita
filtro

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: comentario, dtype: bool

## Extraer a todos los números de longitud 4 de cada registro de la columna comentarios

In [125]:
clientes["comentario"].str.extract(r"([0-9]{4})") #--. Recordar que en extract el patrón siempre va entre paréntes

      0
0  2022
1   NaN
2   NaN
3   NaN
4  2024
5  2023
6  2025
7   NaN

# Extraer todos los dominios de los correos electrónicos y posteriormente hacer el conteo de cada registro. Para saber cuántos clientes se tienen por cada dominio.

In [126]:
clientes

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025,443.222.9988
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345

In [127]:
## 1. Extracción \w : culauier letra o número  [\w]+  ---> 1 o más veces
clientes["dominio"]= clientes["correo"].str.extract(r"@([\w]+)")
clientes

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678,gmail
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543,hotmail
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567,empresa
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono,NaN
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888,yahoo
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222,gmail
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025,443.222.9988,outlook
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345,NaN

In [128]:
clientes.groupby("dominio")["id_cliente"].count()

dominio
empresa    1
gmail      2
hotmail    1
outlook    1
yahoo      1
Name: id_cliente, dtype: int64

In [129]:
clientes["correo"].isna().sum()

np.int64(1)

In [130]:
# Validar si un correo electrónico cumple con ser correo válido
filtro = clientes["correo"].str.contains(r"[\w._]+@[\w._]+", na= False)
filtro

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
Name: correo, dtype: bool

In [131]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678,gmail
1,2,Luis Pérez,luis_perez@hotmail.com,222 987 6543,CLI-245,Debe actualizar correo,2229876543,hotmail
2,3,Marta Gómez,marta@empresa.mx,(999)1234567,USR-100,Compra mensual - VIP,(999)1234567,empresa
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888,yahoo
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222,gmail
6,7,Laura Sánchez,laura.sanchez@outlook.com,443.222.9988,CLI-045,Requiere seguimiento en 2025,443.222.9988,outlook

## Registros con correos electrónicos no válidos

In [132]:
filtro = ~clientes["correo"].str.contains(r"[\w._]+@[\w._]+", na= False)  # Negación en filtro en pandas usar ~
filtro

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
Name: correo, dtype: bool

In [133]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono,NaN
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345,NaN

In [134]:
# \w = [A-Za-z0-9]
filtro = clientes["correo"].str.contains(r"[\w._]+@[\w._]+", na= False)  # Negación en filtro en pandas usar ~
# * 0 o más elementos
# + 1 o más elementos
clientes[~filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono,NaN
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345,NaN

In [135]:
filtro = clientes["correo"].str.contains(r"[\w._]{3}@[\w._]+", na= False)  # Negación en filtro en pandas usar ~
# * 0 o más elementos
# + 1 o más elementos
clientes[~filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
3,4,Carlos Díaz,NaN,sin telefono,CLI-ABC,Teléfono pendiente,sintelefono,NaN
7,8,Miguel Herrera,miguel#correo.com,12345,USR-XYZ,Sin información adicional,12345,NaN

## Regresar los registros que contengan una fecha válida
## Extraer de los registros anteriores la fecha

In [148]:
# Patrón para detectar fechas válidas
filtro = clientes["comentario"].str.contains(r"[0-9]{2}(/|-)[0-9]{2}(/|-)[0-9]{4}")
filtro

C:\Users\Jessan\AppData\Local\Temp\ipykernel_21536\4269990515.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  filtro = clientes["comentario"].str.contains(r"[0-9]{2}(/|-)[0-9]{2}(/|-)[0-9]{4}")

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
Name: comentario, dtype: bool

In [147]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222,gmail

In [143]:
filtro = clientes["comentario"].str.contains(r"\d{2}/|-\d{2}/|-\d{4}")
filtro

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
Name: comentario, dtype: bool

In [149]:
df = clientes[filtro]
df

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222,gmail

# Extracción de fecha

In [153]:
clientes["comentario"].str.extract(r"(\d{2}[/|-]\d{2}[/|-]\d{4})")

            0
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5  15/03/2023
6         NaN
7         NaN

In [155]:
df["comentario"].str.extract(r"(\d{2}[/|-]\d{2}[/|-]\d{4})")
df

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
5,6,Pedro Torres,pedro.torres@gmail,+52 55 1111 2222,VIP-777,Registrado el 15/03/2023,525511112222,gmail

## Registros que en el campo de comentario contiene la palabra Cliente sin importar si esta en mayusculas o minusculas o combinado

In [159]:
filtro = clientes["comentario"].str.contains(r"cliente", case =  False)

In [160]:
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678,gmail
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888,yahoo

In [162]:
filtro = clientes["comentario"].str.upper().str.contains(r"CLIENTE")
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678,gmail
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888,yahoo

In [164]:
filtro = clientes["comentario"].str.lower().str.contains(r"cliente")
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678,gmail
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888,yahoo

In [165]:
filtro = clientes["comentario"].str.contains(r"cliente|CLIENTE|Cliente")
clientes[filtro]

,id_cliente,nombre,correo,telefono,codigo_cliente,comentario,telefono_formato,dominio
0,1,Ana López,ana.lopez@gmail.com,55-1234-5678,CLI-001,Cliente frecuente desde 2022 | 2025,5512345678,gmail
4,5,Sofía Ruiz,sofia.ruiz@yahoo.com,81-5555-8888,CLI-999,Cliente nuevo 2024,8155558888,yahoo

In [168]:
import re ## Biblioteca pora manejar patrones en cadenas

pattern = "cliente"
text = "CliEnte is powerful. python is versatile."
matches = re.findall(pattern, text, flags=re.IGNORECASE)
print(matches)

['CliEnte']

In [172]:
def encontrar_patron(comentario):
    return re.findall("cliente", comentario, flags=re.IGNORECASE )

In [179]:
clientes["comentario"].apply(encontrar_patron)

0    [Cliente]
1           []
2           []
3           []
4    [Cliente]
5           []
6           []
7           []
Name: comentario, dtype: object

In [174]:
# Extraer .com .mx de un correo electrónico

In [197]:
resultado = clientes["correo"].str.extract(r"(@.*.)")[0]
resultado

0      @gmail.com
1    @hotmail.com
2     @empresa.mx
3             NaN
4      @yahoo.com
5          @gmail
6    @outlook.com
7             NaN
Name: 0, dtype: object

In [219]:
def separar_correo(correo):
    #print(type(correo))
    print("Correo: ", correo)
    
    if isinstance(correo, str):
        print(correo.split("."))
        return correo.split(".")[-1]    
    return ""
    
clientes["correo"].apply(separar_correo)

Correo:  ana.lopez@gmail.com
['ana', 'lopez@gmail', 'com']
Correo:  luis_perez@hotmail.com
['luis_perez@hotmail', 'com']
Correo:  marta@empresa.mx
['marta@empresa', 'mx']
Correo:  nan
Correo:  sofia.ruiz@yahoo.com
['sofia', 'ruiz@yahoo', 'com']
Correo:  pedro.torres@gmail
['pedro', 'torres@gmail']
Correo:  laura.sanchez@outlook.com
['laura', 'sanchez@outlook', 'com']
Correo:  miguel#correo.com
['miguel#correo', 'com']

0             com
1             com
2              mx
3
4             com
5    torres@gmail
6             com
7             com
Name: correo, dtype: object

In [ ]:
resultado = clientes["correo"].str.extract(r"(@.*.)")[0]
resultado

In [220]:
clientes["correo"].str.extract(r"\.([A-Za-z]+)$")

     0
0  com
1  com
2   mx
3  NaN
4  com
5  NaN
6  com
7  com