## Pandas y sus aplicaciones

Documentación oficial:
https://pandas.pydata.org/docs/

In [3]:
!pip show pandas

Name: pandas
Version: 2.3.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2023, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: C:\Users\Jessan\anaconda3\envs\MLOps-project-fast-api\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: feature_engine, seaborn, statsmodels, streamlit

In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\jessan\anaconda3\envs\mlops-project-fast-api\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\jessan\anaconda3\envs\mlops-project-fast-api\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jessan\anaconda3\envs\mlops-project-fast-api\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jessan\anaconda3\envs\mlops-project-fast-api\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jessan\anaconda3\envs\mlops-project-fast-api\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\jessan\anaconda3\envs\mlops-project-fast-api\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd

- Python : Funciones nativas para la lógica del programa
- Numpy : Manejo de números
- Pandas : Manejo de datos tabulares

In [6]:
ventas_tienda = pd.DataFrame( # El DataFrame recibe un diccionario
    {
    "producto": ["Café", "Té", "Jugo", "Café", "Té"],
    "sucursal": ["Centro", "Centro", "Norte", "Norte", "Centro"],
    "mes": ["Enero", "Enero", "Enero", "Febrero", "Febrero"],
    "ventas": [1200, 800, 650, 1400, 850]
    }
)

print(ventas_tienda)

  producto sucursal      mes  ventas
0     Café   Centro    Enero    1200
1       Té   Centro    Enero     800
2     Jugo    Norte    Enero     650
3     Café    Norte  Febrero    1400
4       Té   Centro  Febrero     850

In [7]:
ventas_tienda

  producto sucursal      mes  ventas
0     Café   Centro    Enero    1200
1       Té   Centro    Enero     800
2     Jugo    Norte    Enero     650
3     Café    Norte  Febrero    1400
4       Té   Centro  Febrero     850

In [8]:
print("Filas y columnas ", ventas_tienda.shape)

Filas y columnas  (5, 4)

In [10]:
print("Nombre de las columnas: ", list(ventas_tienda.columns))

Nombre de las columnas:  ['producto', 'sucursal', 'mes', 'ventas']

In [11]:
ventas_tienda.describe()

            ventas
count     5.000000
mean    980.000000
std     309.434969
min     650.000000
25%     800.000000
50%     850.000000
75%    1200.000000
max    1400.000000

In [12]:
indicadores_economicos = pd.DataFrame(
{
    "anio": [2020, 2021, 2022, 2023, 2024],
    "inflacion": [2.4, 3.1, 5.8, 4.2, 3.6],
    "desempleo": [7.5, 7.1, 6.4, 5.9, 5.7],
    "crecimiento_pib": [-7.0, 5.5, 3.8, 2.6, 2.9]
})

indicadores_economicos

   anio  inflacion  desempleo  crecimiento_pib
0  2020        2.4        7.5             -7.0
1  2021        3.1        7.1              5.5
2  2022        5.8        6.4              3.8
3  2023        4.2        5.9              2.6
4  2024        3.6        5.7              2.9

In [13]:
indicadores_economicos.describe()

              anio  inflacion  desempleo  crecimiento_pib
count     5.000000   5.000000   5.000000         5.000000
mean   2022.000000   3.820000   6.520000         1.560000
std       1.581139   1.289186   0.769415         4.916605
min    2020.000000   2.400000   5.700000        -7.000000
25%    2021.000000   3.100000   5.900000         2.600000
50%    2022.000000   3.600000   6.400000         2.900000
75%    2023.000000   4.200000   7.100000         3.800000
max    2024.000000   5.800000   7.500000         5.500000

In [14]:
indicadores_economicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   anio             5 non-null      int64
 1   inflacion        5 non-null      float64
 2   desempleo        5 non-null      float64
 3   crecimiento_pib  5 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 292.0 bytes

## Series

In [19]:
serie_ventas= pd.Series([120, 150, 180, 170], 
                         index=["Monday", "Tuesday", "Wednesday", "Thursday"])

In [20]:
serie_ventas

Monday       120
Tuesday      150
Wednesday    180
Thursday     170
dtype: int64

In [22]:
print("Valores: ", serie_ventas.values)
print("Tipo de datos: ", type(serie_ventas.values))

Valores:  [120 150 180 170]
Tipo de datos:  <class 'numpy.ndarray'>

In [24]:
print("Indice: ", list(serie_ventas.index))

Indice:  ['Monday', 'Tuesday', 'Wednesday', 'Thursday']

In [25]:
print("Tipo dato: ", serie_ventas.dtype)

Tipo dato:  int64

In [26]:
print("Cantidad de elementos de una serie: ", serie_ventas.size)

Cantidad de elementos de una serie:  4

In [27]:

print("¿Cuál es el valor de Monday? ", serie_ventas["Monday"])

¿Cuál es el valor de Monday?  120

In [30]:
print("Subconjunto: \n", serie_ventas[0:2]) # Subconjunto con los elementos de las posiciones 0 y 1

Subconjunto:
 Monday     120
Tuesday    150
dtype: int64

In [31]:
empleados_empresa = pd.DataFrame({
    "empleado": ["E001", "E002", "E003", "E004", "E005"],
    "departamento": ["Ventas", "Finanzas", "Ventas", "Operaciones", "Finanzas"],
    "salario": [2200, 3100, 2400, 2800, 3300],
    "antiguedad_anios": [2, 5, 3, 4, 6]
})

empleados_empresa

  empleado departamento  salario  antiguedad_anios
0     E001       Ventas     2200                 2
1     E002     Finanzas     3100                 5
2     E003       Ventas     2400                 3
3     E004  Operaciones     2800                 4
4     E005     Finanzas     3300                 6

In [32]:
empleados_empresa.shape

(5, 4)

In [33]:
empleados_empresa.head() #Regresa los primeros 5 elementos del dataframe

  empleado departamento  salario  antiguedad_anios
0     E001       Ventas     2200                 2
1     E002     Finanzas     3100                 5
2     E003       Ventas     2400                 3
3     E004  Operaciones     2800                 4
4     E005     Finanzas     3300                 6

In [34]:
empleados_empresa.head(2)

  empleado departamento  salario  antiguedad_anios
0     E001       Ventas     2200                 2
1     E002     Finanzas     3100                 5

In [35]:
renombre_empleados_df =  empleados_empresa.rename(
    columns = {
        "empleado": "Empleado",
        "departamento": "Departamento",
        "salario" : "Salario",
        "antiguedad_anios": "Antigüedad"
    }
)

#cve_pais

In [36]:
renombre_empleados_df

  Empleado Departamento  Salario  Antigüedad
0     E001       Ventas     2200           2
1     E002     Finanzas     3100           5
2     E003       Ventas     2400           3
3     E004  Operaciones     2800           4
4     E005     Finanzas     3300           6

In [41]:
#Creación de nuevas columnas
empleados_empresa["monto_total_pagado"]  =  empleados_empresa["salario"] * (empleados_empresa["antiguedad_anios"]*12)

In [40]:
empleados_empresa

  empleado departamento  salario  antiguedad_anios  calculo
0     E001       Ventas     2200                 2    52800
1     E002     Finanzas     3100                 5   186000
2     E003       Ventas     2400                 3    86400
3     E004  Operaciones     2800                 4   134400
4     E005     Finanzas     3300                 6   237600

In [43]:
empleados_reducido = empleados_empresa.drop(columns = ["empleado"])
empleados_reducido

  departamento  salario  antiguedad_anios  calculo  monto_total_pagado
0       Ventas     2200                 2    52800               52800
1     Finanzas     3100                 5   186000              186000
2       Ventas     2400                 3    86400               86400
3  Operaciones     2800                 4   134400              134400
4     Finanzas     3300                 6   237600              237600