## Pandas

In [1]:
import pandas as pd
import numpy as np

## Serie

In [2]:
ventas_semanales = pd.Series([120, 135, 128, 150, 145])
ventas_semanales.index
ventas_semanales

0    120
1    135
2    128
3    150
4    145
dtype: int64

In [3]:
ventas_semanales = pd.Series([120, 135, 128, 150, 145],
                            index = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes"])

ventas_semanales

Lunes        120
Martes       135
Miércoles    128
Jueves       150
Viernes      145
dtype: int64

In [4]:
ventas_semanales.index

Index(['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'], dtype='object')

In [5]:
print("Ventas del Lunes: ", ventas_semanales["Lunes"])

Ventas del Lunes:  120

In [6]:
filtro = ventas_semanales > 130
ventas_semanales[filtro]

Martes     135
Jueves     150
Viernes    145
dtype: int64

## Dataframe

In [7]:
titulos_peliculas = ['Coco','Titanic','Avatar','Toy Story','Como agua para chocolate']
califaciones_peliculas = np.array([5,3,4,3,5.0])
anios_estrenos = np.array([2017, 1997, 2000, 2015, np.nan])
generos_peliculas = ['infantil','romance','ciencia-ficción', 'infantil','romance']

In [8]:
datos_peliculas = np.column_stack(
    (titulos_peliculas,
    califaciones_peliculas,
    anios_estrenos,
    generos_peliculas)
)

In [9]:
datos_peliculas

array([['Coco', '5.0', '2017.0', 'infantil'],
       ['Titanic', '3.0', '1997.0', 'romance'],
       ['Avatar', '4.0', '2000.0', 'ciencia-ficción'],
       ['Toy Story', '3.0', '2015.0', 'infantil'],
       ['Como agua para chocolate', '5.0', 'nan', 'romance']],
      dtype='<U32')

In [10]:
tabla_peliculas = pd.DataFrame(
    datos_peliculas,
    columns = ['nombre_pelicula', 'calificacion','anio','genero']
)

tabla_peliculas

            nombre_pelicula calificacion    anio           genero
0                      Coco          5.0  2017.0         infantil
1                   Titanic          3.0  1997.0          romance
2                    Avatar          4.0  2000.0  ciencia-ficción
3                 Toy Story          3.0  2015.0         infantil
4  Como agua para chocolate          5.0     nan          romance

In [11]:
tabla_peliculas.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
tabla_peliculas.index = tabla_peliculas['nombre_pelicula']

In [13]:
tabla_peliculas.index

Index(['Coco', 'Titanic', 'Avatar', 'Toy Story', 'Como agua para chocolate'], dtype='object', name='nombre_pelicula')

In [14]:

tabla_peliculas["calificacion"] = tabla_peliculas["calificacion"].astype(float)
tabla_peliculas["anio"] = tabla_peliculas["anio"].astype(float)

tabla_peliculas["calificacion"].dtype

tabla_peliculas["anio"] = tabla_peliculas["anio"].fillna(0)
print(tabla_peliculas["anio"] )
#tabla_peliculas[tabla_peliculas["calificacion"] >= 4]
filtro = tabla_peliculas["calificacion"] >= 4
tabla_peliculas[filtro]

nombre_pelicula
Coco                        2017.0
Titanic                     1997.0
Avatar                      2000.0
Toy Story                   2015.0
Como agua para chocolate       0.0
Name: anio, dtype: float64

,nombre_pelicula,calificacion,anio,genero
nombre_pelicula,,,,
Coco,Coco,5.0,2017.0,infantil
Avatar,Avatar,4.0,2000.0,ciencia-ficción
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance

In [15]:
#Obtener promedio de todas las calificaciones
proomedio = tabla_peliculas["calificacion"].mean()
proomedio

np.float64(4.0)

In [16]:

#pelicula_mas_reciente = tabla_peliculas["anio"].max(numeric_only=True)
#pelicula_mas_antigua = tabla_peliculas["anio"].min(numeric_only=True)
#pelcicula_mas_antigua =
pelicula_mas_reciente = tabla_peliculas["anio"].max()
pelicula_mas_antigua = tabla_peliculas["anio"].min()
print(type(pelicula_mas_reciente))
pelicula_mas_antigua 
anios =  pelicula_mas_antigua - pelicula_mas_reciente
anios

<class 'float'>

-2017.0

# Métodos para poder explorar los datos y columnas, tipos de datos de un data frame

In [17]:
tabla_peliculas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Coco to Como agua para chocolate
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nombre_pelicula  5 non-null      object
 1   calificacion     5 non-null      float64
 2   anio             5 non-null      float64
 3   genero           5 non-null      object
dtypes: float64(2), object(2)
memory usage: 372.0+ bytes

In [18]:
tabla_peliculas.head(2)
#tabla_peliculas.head()

                nombre_pelicula  calificacion    anio    genero
nombre_pelicula
Coco                       Coco           5.0  2017.0  infantil
Titanic                 Titanic           3.0  1997.0   romance

In [19]:
tabla_peliculas.tail()

,nombre_pelicula,calificacion,anio,genero
nombre_pelicula,,,,
Coco,Coco,5.0,2017.0,infantil
Titanic,Titanic,3.0,1997.0,romance
Avatar,Avatar,4.0,2000.0,ciencia-ficción
Toy Story,Toy Story,3.0,2015.0,infantil
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance

In [20]:
tabla_peliculas.tail(2)  #Regresa los últimos dos registros

,nombre_pelicula,calificacion,anio,genero
nombre_pelicula,,,,
Toy Story,Toy Story,3.0,2015.0,infantil
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance

In [21]:
tabla_peliculas.describe() ##estadísticas de las variables cuantitativas o numéricas

       calificacion         anio
count           5.0     5.000000
mean            4.0  1605.800000
std             1.0   897.713039
min             3.0     0.000000
25%             3.0  1997.000000
50%             4.0  2000.000000
75%             5.0  2015.000000
max             5.0  2017.000000

In [22]:
tabla_peliculas.describe(include="all")

       nombre_pelicula  calificacion         anio    genero
count                5           5.0     5.000000         5
unique               5           NaN          NaN         3
top               Coco           NaN          NaN  infantil
freq                 1           NaN          NaN         2
mean               NaN           4.0  1605.800000       NaN
std                NaN           1.0   897.713039       NaN
min                NaN           3.0     0.000000       NaN
25%                NaN           3.0  1997.000000       NaN
50%                NaN           4.0  2000.000000       NaN
75%                NaN           5.0  2015.000000       NaN
max                NaN           5.0  2017.000000       NaN

In [23]:
tabla_peliculas.describe(include="object")

       nombre_pelicula    genero
count                5         5
unique               5         3
top               Coco  infantil
freq                 1         2

In [24]:
tabla_peliculas['genero'].value_counts()

genero
infantil           2
romance            2
ciencia-ficción    1
Name: count, dtype: int64

In [25]:
tabla_peliculas['genero'].value_counts(dropna = False)

genero
infantil           2
romance            2
ciencia-ficción    1
Name: count, dtype: int64

In [26]:
tabla_peliculas.shape

(5, 4)

In [27]:
tabla_peliculas.columns

Index(['nombre_pelicula', 'calificacion', 'anio', 'genero'], dtype='object')

In [28]:
tabla_peliculas["calificacion"].dtype

dtype('float64')

In [29]:
tabla_peliculas["anio"]

nombre_pelicula
Coco                        2017.0
Titanic                     1997.0
Avatar                      2000.0
Toy Story                   2015.0
Como agua para chocolate       0.0
Name: anio, dtype: float64

In [30]:
tabla_peliculas['anio'].value_counts()

anio
2017.0    1
1997.0    1
2000.0    1
2015.0    1
0.0       1
Name: count, dtype: int64

In [31]:
tabla_peliculas[["anio", "genero"]]

                            anio           genero
nombre_pelicula
Coco                      2017.0         infantil
Titanic                   1997.0          romance
Avatar                    2000.0  ciencia-ficción
Toy Story                 2015.0         infantil
Como agua para chocolate     0.0          romance

## Selección de información iloc y loc

In [32]:
tabla_peliculas.loc["Coco"]

nombre_pelicula        Coco
calificacion            5.0
anio                 2017.0
genero             infantil
Name: Coco, dtype: object

In [33]:
tabla_peliculas.loc["Toy Story"]

nombre_pelicula    Toy Story
calificacion             3.0
anio                  2015.0
genero              infantil
Name: Toy Story, dtype: object

In [34]:
tabla_peliculas.iloc[0]

nombre_pelicula        Coco
calificacion            5.0
anio                 2017.0
genero             infantil
Name: Coco, dtype: object

In [35]:
tabla_peliculas.iloc[4]

nombre_pelicula    Como agua para chocolate
calificacion                            5.0
anio                                    0.0
genero                              romance
Name: Como agua para chocolate, dtype: object

In [36]:
#tabla_peliculas.iloc[9]  --> índice no valido

In [37]:
tabla_peliculas.iloc[0:2][["calificacion","anio"]]

                 calificacion    anio
nombre_pelicula
Coco                      5.0  2017.0
Titanic                   3.0  1997.0

In [38]:
type(tabla_peliculas.iloc[3])  #-- serie
tabla_peliculas.iloc[3]["genero"]

'infantil'

In [39]:
print("Tipo de datos: ",type(tabla_peliculas.iloc[3][["genero", "anio"]]))
tabla_peliculas.iloc[3][["genero", "anio"]]

Tipo de datos:  <class 'pandas.core.series.Series'>

genero    infantil
anio        2015.0
Name: Toy Story, dtype: object

Regresar el anio correspondiente a  todas las peliculas cuyo genero es infantil .

In [40]:
# Filtro
filtro =  tabla_peliculas["genero"] == "infantil"
print(filtro)
resultado = tabla_peliculas[filtro]
print(resultado)

print("Se accede solo al anio de las peliculas que cumplen con el filtro anterior")
resultado["anio"]
#Extraer la columna anio

nombre_pelicula
Coco                         True
Titanic                     False
Avatar                      False
Toy Story                    True
Como agua para chocolate    False
Name: genero, dtype: bool
                nombre_pelicula  calificacion    anio    genero
nombre_pelicula
Coco                       Coco           5.0  2017.0  infantil
Toy Story             Toy Story           3.0  2015.0  infantil
Se accede solo al anio de las peliculas que cumplen con el filtro anterior

nombre_pelicula
Coco         2017.0
Toy Story    2015.0
Name: anio, dtype: float64

In [41]:
tabla_peliculas.iloc[0, 1] # [fila, columna]

np.float64(5.0)

In [42]:
tabla_peliculas.iloc[0:2, 1]

nombre_pelicula
Coco       5.0
Titanic    3.0
Name: calificacion, dtype: float64

In [43]:
tabla_peliculas.iloc[0:2, 1:3]

                 calificacion    anio
nombre_pelicula
Coco                      5.0  2017.0
Titanic                   3.0  1997.0

Todas las peliculas cuyo genero sea romance y tenga una calificacion mayor a 4

In [44]:
#Recordar: usar & y cada condicion entre paréntesis
filtro = (tabla_peliculas["genero"] == "romance") & (tabla_peliculas["calificacion"] > 4)
filtro

nombre_pelicula
Coco                        False
Titanic                     False
Avatar                      False
Toy Story                   False
Como agua para chocolate     True
dtype: bool

In [45]:
tabla_peliculas[filtro]

,nombre_pelicula,calificacion,anio,genero
nombre_pelicula,,,,
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance

Filtrar solo el nombre de la pelicula

In [46]:
tabla_peliculas[filtro]["nombre_pelicula"]

print(type(tabla_peliculas[filtro]["nombre_pelicula"]))
tabla_peliculas[filtro]["nombre_pelicula"]

<class 'pandas.core.series.Series'>

nombre_pelicula
Como agua para chocolate    Como agua para chocolate
Name: nombre_pelicula, dtype: object

Agregar columnas a un daframe

Agregar una columna con una etiqueta: Si la pelicula tiene calificacion >= 4 entonces colocar Recomendable
                                      Si la pelicula tiene calificacion < 4 entonce colocar No recomendable

In [47]:
tabla_peliculas["etiqueta_calificacion"] = tabla_peliculas["calificacion"] >= 4
tabla_peliculas["etiqueta_calificacion"]

nombre_pelicula
Coco                         True
Titanic                     False
Avatar                       True
Toy Story                   False
Como agua para chocolate     True
Name: etiqueta_calificacion, dtype: bool

In [48]:
# 1. Crear una función
def crear_etiqueta(calificacion):
    """if calificacion >= 4:
        return "Recomendable"
    else:
        return "No recomendable"
        """
    return  "Recomendable" if calificacion >= 4 else "No recomendable"

print("Etiqueta: " , crear_etiqueta(5))
    
# 2.Aplicar esa función a una columna en específico
tabla_peliculas["etiqueta_recomendacion"] =  tabla_peliculas["calificacion"].apply(crear_etiqueta)

Etiqueta:  Recomendable

In [49]:
tabla_peliculas

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion
nombre_pelicula,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable

Crear una columna con una etiqueta: si el anio > 2000 entonces poner reciente, en otro caso colocar antigua

In [50]:
# 1. Crear función
def crear_etiqueta_anio(anio):
    return "Reciente" if anio > 2000 else "Antigua"
# Se valida que funcione correctamente crear_etiqueta_anio
crear_etiqueta_anio(1800)   
# 2. Aplicar la funcion a la columna anio
tabla_peliculas['etiqueta_antiguedad'] = tabla_peliculas['anio'].apply(crear_etiqueta_anio)

In [51]:
tabla_peliculas

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua

In [52]:
tabla_peliculas[tabla_peliculas["genero"].isin(["infantil", "romance"])]

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua

In [53]:
filtro = (tabla_peliculas["genero"] == "infantil") | (tabla_peliculas["genero"] == "romance") 
tabla_peliculas[filtro]

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua

# Ordenamientos por columnas

In [54]:
tabla_peliculas.sort_values("calificacion") # POr defecto se ordena de menor a mayor

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua

In [55]:
tabla_peliculas.sort_values("calificacion", ascending = False)

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente

In [56]:
tabla_peliculas.sort_values("calificacion", ascending = True)

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua

In [57]:
tabla_peliculas.sort_values(["calificacion","anio"])

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente

In [58]:
tabla_peliculas.sort_values(["calificacion","anio"], ascending = [False, False])

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua

# Renombre de columnas

In [59]:
tabla_peliculas_renombre =  tabla_peliculas.rename(columns={"anio":"año de lanzamiento", "nombre_pelicula": "nombre"})
                                                            #diccionario  nombre_anterior: nuevo_nombre
tabla_peliculas_renombre

,nombre,calificacion,año de lanzamiento,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua

Eliminar columnas

In [60]:
tabla_peliculas_renombre= tabla_peliculas.drop(columns=["etiqueta_calificacion"])
                                                       # Recibe una lista con el nombre de las columnas a eliminar
tabla_peliculas_renombre

,nombre_pelicula,calificacion,anio,genero,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,
Coco,Coco,5.0,2017.0,infantil,Recomendable,Reciente
Titanic,Titanic,3.0,1997.0,romance,No recomendable,Antigua
Avatar,Avatar,4.0,2000.0,ciencia-ficción,Recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,No recomendable,Reciente
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,Recomendable,Antigua

# Agrupamiento : groupby

In [61]:
tabla_peliculas.groupby("genero")["calificacion"].mean()

genero
ciencia-ficción    4.0
infantil           4.0
romance            4.0
Name: calificacion, dtype: float64

agrupar por etiqueta de recomendacion y sacar el promedio de cada grupo

In [62]:
tabla_peliculas.groupby("etiqueta_recomendacion")["calificacion"].mean()

etiqueta_recomendacion
No recomendable    3.000000
Recomendable       4.666667
Name: calificacion, dtype: float64

In [63]:
tabla_peliculas.groupby("etiqueta_recomendacion")["calificacion"].mean().sort_values(ascending = False)

etiqueta_recomendacion
Recomendable       4.666667
No recomendable    3.000000
Name: calificacion, dtype: float64

agrupar por año y obtener el promedio de peliculas por año

In [64]:
tabla_peliculas.groupby("anio")["calificacion"].mean().sort_values(ascending =  False).index

Index([0.0, 2017.0, 2000.0, 1997.0, 2015.0], dtype='float64', name='anio')

In [65]:
tabla_peliculas.groupby("anio")["calificacion"].mean().sort_values(ascending =  False)

anio
0.0       5.0
2017.0    5.0
2000.0    4.0
1997.0    3.0
2015.0    3.0
Name: calificacion, dtype: float64

In [66]:
tabla_peliculas.groupby("anio")["calificacion"].mean().sort_index()

anio
0.0       5.0
1997.0    3.0
2000.0    4.0
2015.0    3.0
2017.0    5.0
Name: calificacion, dtype: float64

In [67]:
tabla_peliculas.groupby("anio")["calificacion"].mean().reset_index().sort_values("anio")

     anio  calificacion
0     0.0           5.0
1  1997.0           3.0
2  2000.0           4.0
3  2015.0           3.0
4  2017.0           5.0

In [68]:
tabla_peliculas.sort_values("anio")

,nombre_pelicula,calificacion,anio,genero,etiqueta_calificacion,etiqueta_recomendacion,etiqueta_antiguedad
nombre_pelicula,,,,,,,
Como agua para chocolate,Como agua para chocolate,5.0,0.0,romance,True,Recomendable,Antigua
Titanic,Titanic,3.0,1997.0,romance,False,No recomendable,Antigua
Avatar,Avatar,4.0,2000.0,ciencia-ficción,True,Recomendable,Antigua
Toy Story,Toy Story,3.0,2015.0,infantil,False,No recomendable,Reciente
Coco,Coco,5.0,2017.0,infantil,True,Recomendable,Reciente

## Fechas

In [69]:
tabla_ventas = pd.DataFrame(
    {
    "producto": ["Laptop", "Mouse", "Teclado", "Monitor", "Audífonos"],
    "fecha_venta": ["2025-01-10", "2025-02-15", "2025-03-01", "2025-03-20", "2025-04-05"],
    "monto": [18000, 450, 950, 4200, 1200]
})

print(tabla_ventas)

    producto fecha_venta  monto
0     Laptop  2025-01-10  18000
1      Mouse  2025-02-15    450
2    Teclado  2025-03-01    950
3    Monitor  2025-03-20   4200
4  Audífonos  2025-04-05   1200

In [70]:
print(tabla_ventas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   producto     5 non-null      object
 1   fecha_venta  5 non-null      object
 2   monto        5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
None

In [71]:
print(tabla_ventas["fecha_venta"].dtypes)

object

In [72]:
tabla_ventas["fecha_venta"] = pd.to_datetime(tabla_ventas["fecha_venta"])

In [73]:
print(tabla_ventas["fecha_venta"].dtypes)

datetime64[ns]

In [74]:
tabla_ventas["dia"] = tabla_ventas["fecha_venta"].dt.day
tabla_ventas

    producto fecha_venta  monto  dia
0     Laptop  2025-01-10  18000   10
1      Mouse  2025-02-15    450   15
2    Teclado  2025-03-01    950    1
3    Monitor  2025-03-20   4200   20
4  Audífonos  2025-04-05   1200    5

In [75]:
tabla_ventas["mes"] = tabla_ventas["fecha_venta"].dt.month
tabla_ventas

    producto fecha_venta  monto  dia  mes
0     Laptop  2025-01-10  18000   10    1
1      Mouse  2025-02-15    450   15    2
2    Teclado  2025-03-01    950    1    3
3    Monitor  2025-03-20   4200   20    3
4  Audífonos  2025-04-05   1200    5    4

In [76]:
tabla_ventas["anio"] = tabla_ventas["fecha_venta"].dt.year
tabla_ventas

    producto fecha_venta  monto  dia  mes  anio
0     Laptop  2025-01-10  18000   10    1  2025
1      Mouse  2025-02-15    450   15    2  2025
2    Teclado  2025-03-01    950    1    3  2025
3    Monitor  2025-03-20   4200   20    3  2025
4  Audífonos  2025-04-05   1200    5    4  2025

In [77]:
tabla_ventas["trimestre"] = tabla_ventas["fecha_venta"].dt.quarter
tabla_ventas

    producto fecha_venta  monto  dia  mes  anio  trimestre
0     Laptop  2025-01-10  18000   10    1  2025          1
1      Mouse  2025-02-15    450   15    2  2025          1
2    Teclado  2025-03-01    950    1    3  2025          1
3    Monitor  2025-03-20   4200   20    3  2025          1
4  Audífonos  2025-04-05   1200    5    4  2025          2

In [78]:
tabla_ventas["dia_semana"] = tabla_ventas["fecha_venta"].dt.dayofweek
tabla_ventas

    producto fecha_venta  monto  dia  mes  anio  trimestre  dia_semana
0     Laptop  2025-01-10  18000   10    1  2025          1           4
1      Mouse  2025-02-15    450   15    2  2025          1           5
2    Teclado  2025-03-01    950    1    3  2025          1           5
3    Monitor  2025-03-20   4200   20    3  2025          1           3
4  Audífonos  2025-04-05   1200    5    4  2025          2           5

In [79]:
tabla_ventas["nombre_dia"] = tabla_ventas["fecha_venta"].dt.day_name()
print(type(tabla_ventas["dia_semana"]))
tabla_ventas.iloc[0]["dia_semana"]

<class 'pandas.core.series.Series'>

np.int32(4)

In [80]:
tabla_ventas

,producto,fecha_venta,monto,dia,mes,anio,trimestre,dia_semana,nombre_dia
0,Laptop,2025-01-10,18000,10,1,2025,1,4,Friday
1,Mouse,2025-02-15,450,15,2,2025,1,5,Saturday
2,Teclado,2025-03-01,950,1,3,2025,1,5,Saturday
3,Monitor,2025-03-20,4200,20,3,2025,1,3,Thursday
4,Audífonos,2025-04-05,1200,5,4,2025,2,5,Saturday

In [81]:
nombres_dias = {
    0: "lunes",
    1: "martes",
    2: "miércoles",
    3: "jueves",
    4: "viernes",
    5: "sábado",
    6: "domingo"
}

nombres_meses = {
    1: "enero",
    2: "febrero",
    3: "marzo",
    4: "abril",
    5: "mayo",
    6: "junio",
    7: "julio",
    8: "agosto",
    9: "septiembre",
    10: "octubre",
    11: "noviembre",
    12: "diciembre"
}


## Mapeo de valores para hacer la sustición 
tabla_ventas["nombre_dia"] = tabla_ventas["dia_semana"].map(nombres_dias)
tabla_ventas["nombre_mes"] = tabla_ventas["mes"].map(nombres_meses)
tabla_ventas

,producto,fecha_venta,monto,dia,mes,anio,trimestre,dia_semana,nombre_dia,nombre_mes
0,Laptop,2025-01-10,18000,10,1,2025,1,4,viernes,enero
1,Mouse,2025-02-15,450,15,2,2025,1,5,sábado,febrero
2,Teclado,2025-03-01,950,1,3,2025,1,5,sábado,marzo
3,Monitor,2025-03-20,4200,20,3,2025,1,3,jueves,marzo
4,Audífonos,2025-04-05,1200,5,4,2025,2,5,sábado,abril

El monto total de todas las ventas del mes marzo

In [82]:
filtro =  tabla_ventas["mes"] == 3
filtro 
tabla_ventas[filtro]["monto"].sum()

np.int64(5150)

Obtener el mes con mayor ganancia

In [83]:
tabla_ventas.groupby("nombre_mes")["monto"].sum()
tabla_ventas.groupby("nombre_mes")["monto"].sum().reset_index().sort_values("nombre_mes").max()

nombre_mes    marzo
monto         18000
dtype: object

In [85]:
tabla = pd.pivot_table(tabla_ventas, index='nombre_mes', values='monto' , aggfunc='sum')
tabla.sort_values(by='monto', ascending = False).head(1)

            monto
nombre_mes
enero       18000

In [90]:
tabla_ventas.groupby("nombre_mes")["monto"].sum().idxmax()

'enero'

In [ ]:
#dt.month_name()
tabla_ventas.groupby(tabla_ventas["fecha_venta"].dt.month_name())["monto"].sum()