# Pandas

In [74]:
import pandas as pd

In [75]:
citas = pd.DataFrame({
    "id_cita": [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412],
    "paciente": ["Ana", "Luis", "Marta", "Carlos", "Sofía", "Pedro", "Laura", "Miguel", "Elena", "Jorge", "Daniela", "Raúl"],
    "ciudad": ["CDMX", "Puebla", "CDMX", "Mérida", "Puebla", "Monterrey", "CDMX", "Mérida", "Puebla", "CDMX", "Monterrey", "Puebla"],
    "especialidad": ["Cardiología", "Dermatología", "Oncología", "Cardiología", "Medicina General", "Oncología", "Dermatología", "Medicina General", "Cardiología", "Oncología", "Cardiología", "Dermatología"],
    "edad": [45, 32, 58, 63, 27, 70, 40, 35, 52, 61, 48, 29],
    "fecha_cita": [
        "2025-01-08", "2025-01-15", "2025-02-03", "2025-02-18", "2025-02-25", "2025-03-04",
        "2025-03-12", "2025-03-20", "2025-04-02", "2025-04-10", "2025-04-15", "2025-05-05"
    ],
    "estado": ["Asistió", "Cancelada", "Asistió", "Asistió", "Cancelada", "Asistió", "No asistió", "Asistió", "Cancelada", "Asistió", "Asistió", "No asistió"],
    "costo": [1200, 800, 2000, 1300, 600, 2200, 850, 650, 1250, 2100, 1350, 900]
})

citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,1300
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,2200
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,900

In [76]:
citas["fecha_cita"] = pd.to_datetime(citas["fecha_cita"])

In [77]:
citas.shape

(12, 8)

In [78]:
citas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_cita       12 non-null     int64
 1   paciente      12 non-null     object
 2   ciudad        12 non-null     object
 3   especialidad  12 non-null     object
 4   edad          12 non-null     int64
 5   fecha_cita    12 non-null     datetime64[ns]
 6   estado        12 non-null     object
 7   costo         12 non-null     int64
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 900.0+ bytes

In [79]:
citas.describe()

          id_cita       edad           fecha_cita        costo
count   12.000000  12.000000                   12    12.000000
mean   406.500000  46.666667  2025-03-07 10:00:00  1266.666667
min    401.000000  27.000000  2025-01-08 00:00:00   600.000000
25%    403.750000  34.250000  2025-02-14 06:00:00   837.500000
50%    406.500000  46.500000  2025-03-08 00:00:00  1225.000000
75%    409.250000  58.750000  2025-04-04 00:00:00  1512.500000
max    412.000000  70.000000  2025-05-05 00:00:00  2200.000000
std      3.605551  14.373798                  NaN   561.383572

In [80]:
citas.describe(include = "object")

       paciente ciudad especialidad   estado
count        12     12           12       12
unique       12      4            4        3
top         Ana   CDMX  Cardiología  Asistió
freq          1      4            4        7

In [81]:
#value_counts()
citas.value_counts()

id_cita  paciente  ciudad     especialidad      edad  fecha_cita  estado      costo
401      Ana       CDMX       Cardiología       45    2025-01-08  Asistió     1200     1
402      Luis      Puebla     Dermatología      32    2025-01-15  Cancelada   800      1
403      Marta     CDMX       Oncología         58    2025-02-03  Asistió     2000     1
404      Carlos    Mérida     Cardiología       63    2025-02-18  Asistió     1300     1
405      Sofía     Puebla     Medicina General  27    2025-02-25  Cancelada   600      1
406      Pedro     Monterrey  Oncología         70    2025-03-04  Asistió     2200     1
407      Laura     CDMX       Dermatología      40    2025-03-12  No asistió  850      1
408      Miguel    Mérida     Medicina General  35    2025-03-20  Asistió     650      1
409      Elena     Puebla     Cardiología       52    2025-04-02  Cancelada   1250     1
410      Jorge     CDMX       Oncología         61    2025-04-10  Asistió     2100     1
411      Daniela   Monterrey  Cardiología       48    2025-04-15  Asistió     1350     1
412      Raúl      Puebla     Dermatología      29    2025-05-05  No asistió  900      1
Name: count, dtype: int64

In [82]:
citas["ciudad"].value_counts()

ciudad
CDMX         4
Puebla       4
Mérida       2
Monterrey    2
Name: count, dtype: int64

In [83]:
citas["estado"].value_counts()

estado
Asistió       7
Cancelada     3
No asistió    2
Name: count, dtype: int64

In [84]:
citas["especialidad"].value_counts()

especialidad
Cardiología         4
Dermatología        3
Oncología           3
Medicina General    2
Name: count, dtype: int64

In [85]:
citas["costo"].value_counts()

costo
1200    1
800     1
2000    1
1300    1
600     1
2200    1
850     1
650     1
1250    1
2100    1
1350    1
900     1
Name: count, dtype: int64

In [86]:
citas.index

RangeIndex(start=0, stop=12, step=1)

In [87]:
citas.set_index("id_cita")

,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
id_cita,,,,,,,
401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200
402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,800
403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000
404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,1300
405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600
406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,2200
407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850
408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650
409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250
410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100
411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350
412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,900

In [88]:
#Diferencias entre loc y iloccitas
citas.iloc[0]

id_cita                         401
paciente                        Ana
ciudad                         CDMX
especialidad            Cardiología
edad                             45
fecha_cita      2025-01-08 00:00:00
estado                      Asistió
costo                          1200
Name: 0, dtype: object

In [89]:
citas.iloc[0:4,]

   id_cita paciente  ciudad  especialidad  edad fecha_cita     estado  costo
0      401      Ana    CDMX   Cardiología    45 2025-01-08    Asistió   1200
1      402     Luis  Puebla  Dermatología    32 2025-01-15  Cancelada    800
2      403    Marta    CDMX     Oncología    58 2025-02-03    Asistió   2000
3      404   Carlos  Mérida   Cardiología    63 2025-02-18    Asistió   1300

In [90]:
citas.iloc[0:4, 1:4]

  paciente  ciudad  especialidad
0      Ana    CDMX   Cardiología
1     Luis  Puebla  Dermatología
2    Marta    CDMX     Oncología
3   Carlos  Mérida   Cardiología

In [91]:
citas.loc[0,"ciudad"]

'CDMX'

In [92]:
citas.loc[:5, ["paciente","ciudad","estado"]]

  paciente     ciudad     estado
0      Ana       CDMX    Asistió
1     Luis     Puebla  Cancelada
2    Marta       CDMX    Asistió
3   Carlos     Mérida    Asistió
4    Sofía     Puebla  Cancelada
5    Pedro  Monterrey    Asistió

In [93]:
# Calcular el promedio de las personas que SI asistieron a su cita cuya especialidad es Medicina General o Oncología

filtro =  (citas["estado"] == "Asistió") & ((citas["especialidad"] == "Medicina General") | (citas["especialidad"]== "Oncología"))
citas[filtro]["costo"].mean()
# Calcular el promedio

#Promedio por especialidad
citas[filtro].groupby("especialidad")["costo"].mean()

especialidad
Medicina General     650.0
Oncología           2100.0
Name: costo, dtype: float64

In [94]:

filtro =  (citas["estado"] == "Asistió") & ((citas["especialidad"] == "Medicina General"))
citas[filtro]

   id_cita paciente  ciudad      especialidad  edad fecha_cita   estado  costo
7      408   Miguel  Mérida  Medicina General    35 2025-03-20  Asistió    650

In [95]:
# Registro de personas que acudieron a su cita entre el 1 de enero del 2025 y 31 de marzo del 2025
filtro = (citas["fecha_cita"] >= "01-01-2025") & (citas["fecha_cita"] <= "31-03-2025")

print(citas[filtro]["fecha_cita"])
#.dt.month
print(type(citas[filtro]["fecha_cita"]))

# ¿Cuá´tas pesonas cudieron en esa fecha?

0   2025-01-08
1   2025-01-15
2   2025-02-03
3   2025-02-18
4   2025-02-25
5   2025-03-04
6   2025-03-12
7   2025-03-20
Name: fecha_cita, dtype: datetime64[ns]
<class 'pandas.core.series.Series'>

In [96]:
citas[filtro]["fecha_cita"].dt.month

0    1
1    1
2    2
3    2
4    2
5    3
6    3
7    3
Name: fecha_cita, dtype: int32

In [97]:
## Cantidad de días entre la cita de Ana y de Daniela
filtro = citas["paciente"].isin(["Ana","Daniela"])
subconjunto = citas[filtro]
print(subconjunto)
diferencia = subconjunto.loc[0,"fecha_cita"] - subconjunto.loc[10,"fecha_cita"]
print("Días: ", abs(diferencia) )

    id_cita paciente     ciudad especialidad  edad fecha_cita   estado  costo
0       401      Ana       CDMX  Cardiología    45 2025-01-08  Asistió   1200
10      411  Daniela  Monterrey  Cardiología    48 2025-04-15  Asistió   1350
Días:  97 days 00:00:00

In [98]:
##Agregar
def agrupar_por_edad(edad):
    if edad <= 0:
        return ""
    if edad <= 25:
        return "joven"
    if edad >25 and edad < 65:
        return "adulto"
    return "tercera_edad"

agrupar_por_edad(100)

citas["etiqueta_edad"] =  citas["edad"].apply(agrupar_por_edad)

citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo,etiqueta_edad
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200,adulto
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,800,adulto
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000,adulto
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,1300,adulto
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600,adulto
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,2200,tercera_edad
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850,adulto
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650,adulto
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250,adulto
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100,adulto
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350,adulto
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,900,adulto

In [99]:
## Contar cuantas personas pertencen a cada categoría de acuerdo a la etiqueta_Edad
citas.groupby("etiqueta_edad").count()

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
etiqueta_edad,,,,,,,,
adulto,11,11,11,11,11,11,11,11
tercera_edad,1,1,1,1,1,1,1,1

In [100]:
citas["etiqueta_edad"].value_counts()

etiqueta_edad
adulto          11
tercera_edad     1
Name: count, dtype: int64

In [101]:
citas = pd.DataFrame({
    "id_cita": [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412],
    "paciente": ["Ana", "Luis", "Marta", "Carlos", "Sofía", "Pedro", "Laura", "Miguel", "Elena", "Jorge", "Daniela", "Raúl"],
    "ciudad": ["CDMX", "Puebla", "CDMX", "Mérida", "Puebla", "Monterrey", "CDMX", "Mérida", "Puebla", "CDMX", "Monterrey", "Puebla"],
    "especialidad": ["Cardiología", "Dermatología", "Oncología", "Cardiología", "Medicina General", "Oncología", "Dermatología", "Medicina General", "Cardiología", "Oncología", "Cardiología", "Dermatología"],
    "edad": [45, 32, 58, 63, 27, 70, 40, 35, 52, 61, 48, 29],
    "fecha_cita": [
        "2025-01-08", "", "2025-02-03", "11-04-2025", "2025-02-25", "No existe",
        "2025-03-12", "2025-03-20", "No disponible", "2025-04-10", "2025-04-15", "No registrada"
    ],
    "estado": ["Asistió", "Cancelada", "Asistió", "Asistió", "Cancelada", "Asistió", "No asistió", "Asistió", "Cancelada", "Asistió", "Asistió", "No asistió"],
    "costo": [1200, 800, 2000, 1300, 600, 2200, 850, 650, 1250, 2100, 1350, 900]
})

citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200
1,402,Luis,Puebla,Dermatología,32,,Cancelada,800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000
3,404,Carlos,Mérida,Cardiología,63,11-04-2025,Asistió,1300
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600
5,406,Pedro,Monterrey,Oncología,70,No existe,Asistió,2200
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650
8,409,Elena,Puebla,Cardiología,52,No disponible,Cancelada,1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350
11,412,Raúl,Puebla,Dermatología,29,No registrada,No asistió,900

In [102]:
citas["fecha_cita"] = pd.to_datetime(citas["fecha_cita"], errors = "coerce")

In [103]:
citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200
1,402,Luis,Puebla,Dermatología,32,NaT,Cancelada,800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000
3,404,Carlos,Mérida,Cardiología,63,NaT,Asistió,1300
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600
5,406,Pedro,Monterrey,Oncología,70,NaT,Asistió,2200
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650
8,409,Elena,Puebla,Cardiología,52,NaT,Cancelada,1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350
11,412,Raúl,Puebla,Dermatología,29,NaT,No asistió,900

In [104]:
#Calcular cuantos nan tengo en las fechas de las citas
citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200
1,402,Luis,Puebla,Dermatología,32,NaT,Cancelada,800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000
3,404,Carlos,Mérida,Cardiología,63,NaT,Asistió,1300
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600
5,406,Pedro,Monterrey,Oncología,70,NaT,Asistió,2200
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650
8,409,Elena,Puebla,Cardiología,52,NaT,Cancelada,1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350
11,412,Raúl,Puebla,Dermatología,29,NaT,No asistió,900

In [105]:
#Cuantas valores nan/ NaT existen en la fechas de las citas
citas["fecha_cita"].isna().sum()

np.int64(5)

In [106]:
citas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_cita       12 non-null     int64
 1   paciente      12 non-null     object
 2   ciudad        12 non-null     object
 3   especialidad  12 non-null     object
 4   edad          12 non-null     int64
 5   fecha_cita    7 non-null      datetime64[ns]
 6   estado        12 non-null     object
 7   costo         12 non-null     int64
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 900.0+ bytes

In [107]:
citas["fecha_cita"].dt.month

0     1.0
1     NaN
2     2.0
3     NaN
4     2.0
5     NaN
6     3.0
7     3.0
8     NaN
9     4.0
10    4.0
11    NaN
Name: fecha_cita, dtype: float64

In [108]:
citas["fecha_cita"].dt.year

0     2025.0
1        NaN
2     2025.0
3        NaN
4     2025.0
5        NaN
6     2025.0
7     2025.0
8        NaN
9     2025.0
10    2025.0
11       NaN
Name: fecha_cita, dtype: float64

In [109]:
citas["fecha_cita"].dt.day_name()

0     Wednesday
1           NaN
2        Monday
3           NaN
4       Tuesday
5           NaN
6     Wednesday
7      Thursday
8           NaN
9      Thursday
10      Tuesday
11          NaN
Name: fecha_cita, dtype: object

In [110]:
citas["fecha_cita"].dt.quarter

0     1.0
1     NaN
2     1.0
3     NaN
4     1.0
5     NaN
6     1.0
7     1.0
8     NaN
9     2.0
10    2.0
11    NaN
Name: fecha_cita, dtype: float64

In [111]:
tabla_examenes = pd.DataFrame({
    "estudiante": ["Ana", "Luis", "Sofía", "Carlos"],
    "fecha_examen": ["10/01/2025", "18/02/2025", "05/03/2025", "21/04/2025"]
})

tabla_examenes["fecha_examen"] = pd.to_datetime(
    tabla_examenes["fecha_examen"],
    errors = "coerce"
)

tabla_examenes

  estudiante fecha_examen
0        Ana   2025-10-01
1       Luis          NaT
2      Sofía   2025-05-03
3     Carlos          NaT

In [112]:

tabla_examenes["fecha_examen"] = pd.to_datetime(
    tabla_examenes["fecha_examen"],
    format="%d/%m/%Y"
)

tabla_examenes

  estudiante fecha_examen
0        Ana   2025-10-01
1       Luis          NaT
2      Sofía   2025-05-03
3     Carlos          NaT

## Expresiones regulares

In [113]:
# Creamos una Serie con nombres.
nombres = pd.Series([
    "Ana López",
    "Luis Pérez",
    "Marta Gómez",
    "Carlos Ramíro",
    "Andrea Torres",
    "Pedro Sánchez"
])

nombres

0        Ana López
1       Luis Pérez
2      Marta Gómez
3    Carlos Ramíro
4    Andrea Torres
5    Pedro Sánchez
dtype: object

In [114]:
print(type(nombres.str.contains("Ana", regex=True)))
nombres.str.contains("Ana", regex=True)

<class 'pandas.core.series.Series'>

0     True
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [115]:
filtro = nombres.str.contains("Ana", regex=True)
nombres[filtro]

0    Ana López
dtype: object

In [116]:
filtro =  nombres.str.contains("^A",regex = True)
filtro

0     True
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [117]:
#Nombres que termimen con z
filtro =  nombres.str.contains("z$", regex = True)
filtro

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [118]:
nombres[filtro]

0        Ana López
1       Luis Pérez
2      Marta Gómez
5    Pedro Sánchez
dtype: object

In [119]:
citas = pd.DataFrame({
    "id_cita": [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412],
    "paciente": ["  Ana ", "  Luis ", " Marta ", " Carlos ", "  Sofía ", " Pedro ", " Laura ", "   Miguel ", " Elena  ", "Jorge ", "Daniela ", "Raúl  "],
    "ciudad": ["CDMX", "Puebla", "CDMX", "Mérida", "Puebla", "Monterrey", "CDMX", "Mérida", "Puebla", "CDMX", "Monterrey", "Puebla"],
    "especialidad": ["Cardiología", "Dermatología", "Oncología", "Cardiología", "Medicina General", "Oncología", "Dermatología", "Medicina General", "Cardiología", "Oncología", "Cardiología", "Dermatología"],
    "edad": [45, 32, 58, 63, 27, 70, 40, 35, 52, 61, 48, 29],
    "fecha_cita": [
        "2025-01-08", "2025-01-15", "2025-02-03", "2025-02-18", "2025-02-25", "2025-03-04",
        "2025-03-12", "2025-03-20", "2025-04-02", "2025-04-10", "2025-04-15", "2025-05-05"
    ],
    "estado": ["Asistió", "Cancelada", "Asistió", "Asistió", "Cancelada", "Asistió", "No asistió", "Asistió", "Cancelada", "Asistió", "Asistió", "No asistió"],
    "costo": ["$1,200", "$800", "$2,000", "$13.50", "$600", "$22,002", "$850.35", "$650", "$1250", "$2100", "$1350", "$900"]
})

citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,"$1,200"
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,$800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,"$2,000"
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,$13.50
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,$600
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,"$22,002"
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,$850.35
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,$650
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,$1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,$2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,$1350
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,$900

In [120]:
#Todas los pacientes cuyo nombre empiece con L
filtro = citas["paciente"].str.contains("^L")
filtro

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
Name: paciente, dtype: bool

In [121]:
citas[filtro]

Empty DataFrame
Columns: [id_cita, paciente, ciudad, especialidad, edad, fecha_cita, estado, costo]
Index: []

In [122]:
filtro =  citas["especialidad"].str.contains("ía$", regex=True)
filtro

0      True
1      True
2      True
3      True
4     False
5      True
6      True
7     False
8      True
9      True
10     True
11     True
Name: especialidad, dtype: bool

In [123]:
citas[filtro]

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,"$1,200"
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,$800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,"$2,000"
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,$13.50
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,"$22,002"
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,$850.35
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,$1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,$2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,$1350
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,$900

In [124]:
textos_edades = pd.Series([
    "  Ana tiene 25 años  ",
    "  Luis tiene 31 años ",
    " Marta tiene 28 años ",
    " Carlos tiene 40 años        "
])

textos_edades

print("Longitud incial: ", len(textos_edades[3]))

Longitud incial:  29

In [125]:
sin_espacios =  textos_edades.str.strip()
sin_espacios

0       Ana tiene 25 años
1      Luis tiene 31 años
2     Marta tiene 28 años
3    Carlos tiene 40 años
dtype: object

In [126]:
print("Longitud sin espacios: ", len(sin_espacios[3]))

Longitud sin espacios:  20

In [127]:
edades_extraidas = textos_edades.str.extract(r"(\d+)")
edades_extraidas

    0
0  25
1  31
2  28
3  40

In [128]:
#De la columna monto, quitar los signos de peso y solo tener el número que corresponde al monto
citas["costo"] = citas["costo"].str.replace("$","",regex= False).str.replace(",","", regex = False)
#print(type(citas["costo"]))
#citas["costo"] = citas["costo"].str.replace(",","",regex= False)
citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,13.50
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,22002
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistió,850.35
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,900

In [129]:
print(type(citas["costo"]))

<class 'pandas.core.series.Series'>

In [130]:
citas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_cita       12 non-null     int64
 1   paciente      12 non-null     object
 2   ciudad        12 non-null     object
 3   especialidad  12 non-null     object
 4   edad          12 non-null     int64
 5   fecha_cita    12 non-null     object
 6   estado        12 non-null     object
 7   costo         12 non-null     object
dtypes: int64(2), object(6)
memory usage: 900.0+ bytes

In [131]:
#citas["costo"] = citas["costo"].str.extract(r"(\d+)") ---> Validar el formato del costo, específicamente cuando hay decimal
#citas

In [132]:
citas = pd.DataFrame({
    "id_cita": [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412],
    "paciente": ["  Ana ", "  Luis ", " Marta ", " Carlos ", "  Sofía ", " Pedro ", " Laura ", "   Miguel ", " Elena  ", "Jorge ", "Daniela ", "Raúl  "],
    "ciudad": ["CDMX", "Puebla", "CDMX", "Mérida", "Puebla", "Monterrey", "CDMX", "Mérida", "Puebla", "CDMX", "Monterrey", "Puebla"],
    "especialidad": ["Cardiología", "Dermatología", "Oncología", "Cardiología", "Medicina General", "Oncología", "Dermatología", "Medicina General", "Cardiología", "Oncología", "Cardiología", "Dermatología"],
    "edad": [45, 32, 58, 63, 27, 70, 40, 35, 52, 61, 48, 29],
    "fecha_cita": [
        "2025-01-08", "2025-01-15", "2025-02-03", "2025-02-18", "2025-02-25", "2025-03-04",
        "2025-03-12", "2025-03-20", "2025-04-02", "2025-04-10", "2025-04-15", "2025-05-05"
    ],
    "estado": ["Asistió", "Cancelada", "Asistió", "Asistió", "Cancelada", "Asistió", "No asistio", "Asistió", "Cancelada", "Asistió", "Asistió", "No asistió"],
    "costo": ["$1,200", "$800", "$2,000", "$13.50", "$600", "$22,002", "$850.35", "$650", "$1250", "$2100", "$1350", "$900"]
})

citas

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,"$1,200"
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,$800
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,"$2,000"
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,$13.50
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,$600
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,"$22,002"
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistio,$850.35
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,$650
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,$1250
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,$2100
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,$1350
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,$900

In [133]:
#strip()
#Quitar espacios en blanco al inicio y al final de los nombres de pacientes
citas_copia =  citas.copy()
def quitar_blancos(paciente):
    return paciente.strip()

def longitud(paciente):
    return len(paciente)

citas_copia["Longitud_paciente_antes"] =  citas_copia["paciente"].apply(longitud)
citas_copia["paciente_sin_blancos"] = citas_copia["paciente"].apply(quitar_blancos)
#citas_copia["Longitud_paciente_despues"] =  citas["paciente_sin_blancos"].apply(longitud)
citas_copia

citas_copia["Longitud_después"] =  citas_copia["paciente_sin_blancos"].apply(longitud)
citas_copia

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo,Longitud_paciente_antes,paciente_sin_blancos,Longitud_después
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,"$1,200",6,Ana,3
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,$800,7,Luis,4
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,"$2,000",7,Marta,5
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,$13.50,8,Carlos,6
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,$600,8,Sofía,5
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,"$22,002",7,Pedro,5
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistio,$850.35,7,Laura,5
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,$650,10,Miguel,6
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,$1250,8,Elena,5
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,$2100,6,Jorge,5
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,$1350,8,Daniela,7
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,$900,6,Raúl,4

In [134]:
citas_copia =  citas.copy()
citas_copia["paciente"] = citas_copia["paciente"].str.strip()
citas_copia["longitud_str"] = citas_copia["paciente"].str.len()
citas_copia

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo,longitud_str
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,"$1,200",3
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,$800,4
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,"$2,000",5
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,$13.50,6
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,$600,5
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,"$22,002",5
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistio,$850.35,5
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,$650,6
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,$1250,5
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,$2100,5
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,$1350,7
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,$900,4

In [135]:
print(len(citas_copia["paciente"][0]))

3

In [136]:
#Tarea opciona: Como se manejan los acentos
#citas_no_efectuadas =  citas_copia["estado"].str.contains(r"Cancelada|No asisti", regex = True)
#citas_no_efectuadas
#citas_copia = citas_copia[citas_no_efectuadas]
#citas_copia

In [137]:
citas_copia["costo"] = citas_copia["costo"].str.replace(r"[^0-9.]", "", regex=True)
citas_copia

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo,longitud_str
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200,3
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,800,4
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000,5
3,404,Carlos,Mérida,Cardiología,63,2025-02-18,Asistió,13.50,6
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600,5
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,22002,5
6,407,Laura,CDMX,Dermatología,40,2025-03-12,No asistio,850.35,5
7,408,Miguel,Mérida,Medicina General,35,2025-03-20,Asistió,650,6
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250,5
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100,5
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350,7
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,900,4

In [138]:
# Costos que estén escrito con  cuatro dígitos o más
# Tarea: Patrón para encontrar costos con mas de 4 digitos
filtro = citas_copia["costo"].str.contains(r"^\d{4,}", regex = True)
citas_copia[filtro]
#citas_copia

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo,longitud_str
0,401,Ana,CDMX,Cardiología,45,2025-01-08,Asistió,1200,3
2,403,Marta,CDMX,Oncología,58,2025-02-03,Asistió,2000,5
5,406,Pedro,Monterrey,Oncología,70,2025-03-04,Asistió,22002,5
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250,5
9,410,Jorge,CDMX,Oncología,61,2025-04-10,Asistió,2100,5
10,411,Daniela,Monterrey,Cardiología,48,2025-04-15,Asistió,1350,7

In [139]:
citas_no_efectuadas = citas_copia["estado"].str.contains(
    r"Cancelada|No asistió",
    regex=True
)
citas_copia[citas_no_efectuadas]

,id_cita,paciente,ciudad,especialidad,edad,fecha_cita,estado,costo,longitud_str
1,402,Luis,Puebla,Dermatología,32,2025-01-15,Cancelada,800,4
4,405,Sofía,Puebla,Medicina General,27,2025-02-25,Cancelada,600,5
8,409,Elena,Puebla,Cardiología,52,2025-04-02,Cancelada,1250,5
11,412,Raúl,Puebla,Dermatología,29,2025-05-05,No asistió,900,4

## Ejercicio kahoot

In [140]:
clientes = pd.DataFrame({
    "nombre": ["Ana", "Luis", "Marta", "Carlos"],
    "ciudad": ["CDMX", "Puebla", "Mérida", "Monterrey"],
    "edad": [25, 31, 28, 40]
}, index=["C001", "C002", "C003", "C004"])

clientes

      nombre     ciudad  edad
C001     Ana       CDMX    25
C002    Luis     Puebla    31
C003   Marta     Mérida    28
C004  Carlos  Monterrey    40

In [141]:
clientes.loc["C003"]

nombre     Marta
ciudad    Mérida
edad          28
Name: C003, dtype: object

In [142]:
clientes.iloc[2]

nombre     Marta
ciudad    Mérida
edad          28
Name: C003, dtype: object

In [143]:
clientes.loc["C003", "nombre"]

'Marta'

In [144]:
clientes.loc[["C001", "C003"], ["nombre", "ciudad"]]

     nombre  ciudad
C001    Ana    CDMX
C003  Marta  Mérida

In [145]:

clientes = pd.DataFrame({
    "nombre": ["Ana", "Luis", "Marta"],
    "edad": [25, 31, 28]
})

clientes

  nombre  edad
0    Ana    25
1   Luis    31
2  Marta    28

In [146]:
clientes.loc[0, "nombre"]

'Ana'