In [ ]:
## Dataset Airbnb

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("listings.csv")
df

,id,nombre,id_anfitrion,nombre_anfitrion,grupo_colonia,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3673.0,1,0,NaN,NaN,1,363,0,NaN
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1,NaN
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1,NaN
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1,NaN
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.354480,-99.162170,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27046,1518356968266486778,Suite Frida,674644167,Heyliana,NaN,Venustiano Carranza,19.442240,-99.113440,Private room,1096.0,1,0,NaN,NaN,5,365,0,NaN
27047,1518388105556721163,Habitación a un costado de Ciudad Universitaria,222854336,Marco Antonio,NaN,Coyoacán,19.308017,-99.168158,Private room,260.0,1,0,NaN,NaN,1,365,0,NaN
27048,1518433354720281854,Espacioso departamento en Anzures,470800231,Hector Fernando,NaN,Miguel Hidalgo,19.434460,-99.174010,Entire home/apt,996.0,1,0,NaN,NaN,20,365,0,NaN
27049,1518462568893975567,Casa Roma Baja 05,710857718,Camila,NaN,Cuauhtémoc,19.406435,-99.160934,Entire home/apt,458.0,1,0,NaN,NaN,7,363,0,NaN
27050,1518561444972990747,Departamento con Terraza privada Roma Norte,362149590,Ilse,NaN,Cuauhtémoc,19.413682,-99.154815,Entire home/apt,3082.0,1,0,NaN,NaN,4,365,0,NaN

In [ ]:
df.shape

(27051, 18)

In [ ]:
df.columns

Index(['id', 'nombre', 'id_anfitrion', 'nombre_anfitrion', 'grupo_colonia',
       'colonia', 'latitud', 'longitud', 'tipo_habitacion', 'precio',
       'noches_minimas', 'numero_resenas', 'ultima_resena', 'resenas_por_mes',
       'propiedades_anfitrion', 'disponibilidad_365', 'number_of_reviews_ltm',
       'license'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27051 entries, 0 to 27050
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     27051 non-null  int64
 1   nombre                 27051 non-null  object
 2   id_anfitrion           27051 non-null  int64
 3   nombre_anfitrion       27045 non-null  object
 4   grupo_colonia          0 non-null      float64
 5   colonia                27051 non-null  object
 6   latitud                27051 non-null  float64
 7   longitud               27051 non-null  float64
 8   tipo_habitacion        27051 non-null  object
 9   precio                 23567 non-null  float64
 10  noches_minimas         27051 non-null  int64
 11  numero_resenas         27051 non-null  int64
 12  ultima_resena          23650 non-null  object
 13  resenas_por_mes        23650 non-null  float64
 14  propiedades_anfitrion  27051 non-null  int64
 15  disponibilidad_365     27051 non-null  int64
 16  number_of_reviews_ltm  27051 non-null  int64
 17  license                0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 3.7+ MB

In [ ]:
df.describe()

,id,id_anfitrion,grupo_colonia,latitud,longitud,precio,noches_minimas,numero_resenas,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,license
count,2.705100e+04,2.705100e+04,0.0,27051.000000,27051.000000,23567.000000,27051.000000,27051.000000,23650.000000,27051.000000,27051.000000,27051.000000,0.0
mean,7.003556e+17,2.429439e+08,NaN,19.405490,-99.165385,1792.540841,4.580866,53.777679,1.854855,14.559868,232.686333,15.691028,NaN
std,5.702714e+17,2.062579e+08,NaN,0.042390,0.033535,13230.940558,24.784605,85.143043,2.281154,31.892178,122.270858,23.615517,NaN
min,3.579700e+04,7.365000e+03,NaN,19.177848,-99.339630,61.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000,NaN
25%,4.410472e+07,5.621443e+07,NaN,19.392489,-99.178499,643.000000,1.000000,4.000000,0.450000,1.000000,140.000000,0.000000,NaN
50%,8.307368e+17,1.766835e+08,NaN,19.415390,-99.167100,1039.000000,2.000000,21.000000,1.260000,3.000000,269.000000,7.000000,NaN
75%,1.217382e+18,4.288830e+08,NaN,19.432015,-99.153731,1611.000000,2.000000,69.000000,2.620000,11.000000,341.000000,23.000000,NaN
max,1.518561e+18,7.208445e+08,NaN,19.561010,-98.963360,900000.000000,1125.000000,1434.000000,119.460000,221.000000,365.000000,665.000000,NaN

In [ ]:
df.tail()

,id,nombre,id_anfitrion,nombre_anfitrion,grupo_colonia,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,license
27046,1518356968266486778,Suite Frida,674644167,Heyliana,NaN,Venustiano Carranza,19.442240,-99.113440,Private room,1096.0,1,0,NaN,NaN,5,365,0,NaN
27047,1518388105556721163,Habitación a un costado de Ciudad Universitaria,222854336,Marco Antonio,NaN,Coyoacán,19.308017,-99.168158,Private room,260.0,1,0,NaN,NaN,1,365,0,NaN
27048,1518433354720281854,Espacioso departamento en Anzures,470800231,Hector Fernando,NaN,Miguel Hidalgo,19.434460,-99.174010,Entire home/apt,996.0,1,0,NaN,NaN,20,365,0,NaN
27049,1518462568893975567,Casa Roma Baja 05,710857718,Camila,NaN,Cuauhtémoc,19.406435,-99.160934,Entire home/apt,458.0,1,0,NaN,NaN,7,363,0,NaN
27050,1518561444972990747,Departamento con Terraza privada Roma Norte,362149590,Ilse,NaN,Cuauhtémoc,19.413682,-99.154815,Entire home/apt,3082.0,1,0,NaN,NaN,4,365,0,NaN

In [ ]:
df.head()

,id,nombre,id_anfitrion,nombre_anfitrion,grupo_colonia,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3673.0,1,0,NaN,NaN,1,363,0,NaN
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.41162,-99.17794,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1,NaN
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.43977,-99.15605,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1,NaN
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.41152,-99.16857,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1,NaN
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.35448,-99.16217,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8,NaN

In [ ]:
valores_faltantes =  df.isna().sum().sort_values(ascending= False)
valores_faltantes

license                  27051
grupo_colonia            27051
precio                    3484
resenas_por_mes           3401
ultima_resena             3401
nombre_anfitrion             6
nombre                       0
id                           0
colonia                      0
id_anfitrion                 0
tipo_habitacion              0
longitud                     0
latitud                      0
numero_resenas               0
noches_minimas               0
propiedades_anfitrion        0
disponibilidad_365           0
number_of_reviews_ltm        0
dtype: int64

In [ ]:
# Eliminacion de columna que no contiene ningún dato

del df["license"]  # Es una función de Python
# df.drop(columns=['license'])  -- Mismo resultado pero usando pandas

In [ ]:
df

,id,nombre,id_anfitrion,nombre_anfitrion,grupo_colonia,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3673.0,1,0,NaN,NaN,1,363,0
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.354480,-99.162170,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27046,1518356968266486778,Suite Frida,674644167,Heyliana,NaN,Venustiano Carranza,19.442240,-99.113440,Private room,1096.0,1,0,NaN,NaN,5,365,0
27047,1518388105556721163,Habitación a un costado de Ciudad Universitaria,222854336,Marco Antonio,NaN,Coyoacán,19.308017,-99.168158,Private room,260.0,1,0,NaN,NaN,1,365,0
27048,1518433354720281854,Espacioso departamento en Anzures,470800231,Hector Fernando,NaN,Miguel Hidalgo,19.434460,-99.174010,Entire home/apt,996.0,1,0,NaN,NaN,20,365,0
27049,1518462568893975567,Casa Roma Baja 05,710857718,Camila,NaN,Cuauhtémoc,19.406435,-99.160934,Entire home/apt,458.0,1,0,NaN,NaN,7,363,0
27050,1518561444972990747,Departamento con Terraza privada Roma Norte,362149590,Ilse,NaN,Cuauhtémoc,19.413682,-99.154815,Entire home/apt,3082.0,1,0,NaN,NaN,4,365,0

In [ ]:
df_copia =  df.copy()
df_copia.head()

,id,nombre,id_anfitrion,nombre_anfitrion,grupo_colonia,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3673.0,1,0,NaN,NaN,1,363,0
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.41162,-99.17794,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.43977,-99.15605,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.41152,-99.16857,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.35448,-99.16217,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8

In [ ]:
df_copia = df_copia.drop(columns = ['grupo_colonia'])

In [ ]:
df_copia.head()

,id,nombre,id_anfitrion,nombre_anfitrion,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
0,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,19.38283,-99.27178,Entire home/apt,3673.0,1,0,NaN,NaN,1,363,0
1,44616,Condesa Haus,196253,Fernando,Cuauhtémoc,19.41162,-99.17794,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1
2,56074,Great space in historical San Rafael,265650,Maris,Cuauhtémoc,19.43977,-99.15605,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,Cuauhtémoc,19.41152,-99.16857,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,Coyoacán,19.35448,-99.16217,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8

In [ ]:
df_copia.columns

Index(['id', 'nombre', 'id_anfitrion', 'nombre_anfitrion', 'colonia',
       'latitud', 'longitud', 'tipo_habitacion', 'precio', 'noches_minimas',
       'numero_resenas', 'ultima_resena', 'resenas_por_mes',
       'propiedades_anfitrion', 'disponibilidad_365', 'number_of_reviews_ltm'],
      dtype='object')

In [ ]:
df_copia.isna().mean().sort_values(ascending= False) * 100

precio                   12.879376
ultima_resena            12.572548
resenas_por_mes          12.572548
nombre_anfitrion          0.022180
colonia                   0.000000
id                        0.000000
nombre                    0.000000
id_anfitrion              0.000000
tipo_habitacion           0.000000
longitud                  0.000000
latitud                   0.000000
noches_minimas            0.000000
numero_resenas            0.000000
propiedades_anfitrion     0.000000
disponibilidad_365        0.000000
number_of_reviews_ltm     0.000000
dtype: float64

In [ ]:
## Ver cuantos tipos de habitación tenemos

df_copia['tipo_habitacion'].unique()

array(['Entire home/apt', 'Private room', 'Hotel room', 'Shared room'],
      dtype=object)

In [ ]:
df_copia['tipo_habitacion'].value_counts()
df_copia['tipo_habitacion'].value_counts(normalize = True) # para conocer porcentaje

tipo_habitacion
Entire home/apt    0.654800
Private room       0.332520
Shared room        0.009501
Hotel room         0.003179
Name: proportion, dtype: float64

In [ ]:
df_copia['colonia'].value_counts()

colonia
Cuauhtémoc                12514
Miguel Hidalgo             4573
Benito Juárez              3087
Coyoacán                   1727
Álvaro Obregón              978
Venustiano Carranza         907
Tlalpan                     806
Gustavo A. Madero           515
Iztacalco                   482
Cuajimalpa de Morelos       410
Azcapotzalco                387
Iztapalapa                  302
Xochimilco                  155
La Magdalena Contreras      138
Tláhuac                      40
Milpa Alta                   30
Name: count, dtype: int64

In [ ]:
##Número de reseña

In [ ]:
df_copia['numero_resenas'].max()

1434

In [ ]:
df_copia['numero_resenas'].min()

0

In [ ]:

df_copia['ultima_resena'] = pd.to_datetime(df_copia['ultima_resena'] )
type(df_copia['ultima_resena'] )
df_copia.columns

Index(['id', 'nombre', 'id_anfitrion', 'nombre_anfitrion', 'colonia',
       'latitud', 'longitud', 'tipo_habitacion', 'precio', 'noches_minimas',
       'numero_resenas', 'ultima_resena', 'resenas_por_mes',
       'propiedades_anfitrion', 'disponibilidad_365', 'number_of_reviews_ltm'],
      dtype='object')

In [ ]:
df_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27051 entries, 0 to 27050
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     27051 non-null  int64
 1   nombre                 27051 non-null  object
 2   id_anfitrion           27051 non-null  int64
 3   nombre_anfitrion       27045 non-null  object
 4   colonia                27051 non-null  object
 5   latitud                27051 non-null  float64
 6   longitud               27051 non-null  float64
 7   tipo_habitacion        27051 non-null  object
 8   precio                 23567 non-null  float64
 9   noches_minimas         27051 non-null  int64
 10  numero_resenas         27051 non-null  int64
 11  ultima_resena          23650 non-null  datetime64[ns]
 12  resenas_por_mes        23650 non-null  float64
 13  propiedades_anfitrion  27051 non-null  int64
 14  disponibilidad_365     27051 non-null  int64
 15  number_of_reviews_ltm  27051 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(7), object(4)
memory usage: 3.3+ MB

In [ ]:
# Fecha de la primer reseña
df_copia['ultima_resena'].min()

Timestamp('2013-12-21 00:00:00')

In [ ]:
##Ultima reseña
df_copia['ultima_resena'].max()

Timestamp('2025-09-28 00:00:00')

In [ ]:
# La colonia con más propiedades en Airbnb
df_copia['colonia'].value_counts()

colonia
Cuauhtémoc                12514
Miguel Hidalgo             4573
Benito Juárez              3087
Coyoacán                   1727
Álvaro Obregón              978
Venustiano Carranza         907
Tlalpan                     806
Gustavo A. Madero           515
Iztacalco                   482
Cuajimalpa de Morelos       410
Azcapotzalco                387
Iztapalapa                  302
Xochimilco                  155
La Magdalena Contreras      138
Tláhuac                      40
Milpa Alta                   30
Name: count, dtype: int64

In [ ]:
# Cantidad de colonias en total
len(df_copia["colonia"].unique())
df_copia["colonia"].unique()

array(['Cuajimalpa de Morelos', 'Cuauhtémoc', 'Coyoacán',
       'Miguel Hidalgo', 'Benito Juárez', 'Iztacalco', 'Tlalpan',
       'Venustiano Carranza', 'Gustavo A. Madero', 'Xochimilco',
       'Álvaro Obregón', 'Iztapalapa', 'La Magdalena Contreras',
       'Azcapotzalco', 'Tláhuac', 'Milpa Alta'], dtype=object)

In [ ]:
## Precio pronedio por delegación
df_copia.groupby("colonia")["precio"].mean().sort_values(ascending = False)

colonia
Tlalpan                   2493.466454
Cuajimalpa de Morelos     2150.578797
Cuauhtémoc                2126.383364
Álvaro Obregón            2117.761084
Miguel Hidalgo            1876.386781
Milpa Alta                1420.363636
Coyoacán                  1245.479152
La Magdalena Contreras    1195.074074
Benito Juárez             1120.261867
Xochimilco                1114.150000
Iztacalco                  930.181406
Venustiano Carranza        845.509804
Gustavo A. Madero          821.398693
Iztapalapa                 752.996169
Azcapotzalco               708.098837
Tláhuac                    403.411765
Name: precio, dtype: float64

In [ ]:
## Por delegación contar cuantas noches mínimas permanece una persona
df_copia.groupby("colonia")["noches_minimas"].mean().sort_values(ascending = False)

colonia
Tláhuac                   12.150000
Cuajimalpa de Morelos      8.553659
Tlalpan                    6.820099
La Magdalena Contreras     6.152174
Álvaro Obregón             5.260736
Benito Juárez              5.247813
Azcapotzalco               5.082687
Miguel Hidalgo             4.947955
Coyoacán                   4.353793
Cuauhtémoc                 4.251478
Iztapalapa                 4.132450
Xochimilco                 3.206452
Gustavo A. Madero          2.920388
Venustiano Carranza        2.866593
Iztacalco                  2.122407
Milpa Alta                 1.500000
Name: noches_minimas, dtype: float64

In [ ]:
## Precio promedio por tipo de habitación por cada colonia
#tipo_habitacion
df_copia.groupby(['colonia','tipo_habitacion'])['precio'].mean()
## Manejo de Nan,  eliminar registros con nan, imputar valores del precio(moda, media, mediana, promedio por colonia y tipo de habitación,)

colonia                 tipo_habitacion
Azcapotzalco            Entire home/apt      863.431280
                        Private room         461.669173
Benito Juárez           Entire home/apt     1444.690254
                        Hotel room                  NaN
                        Private room         657.923695
                        Shared room          370.117647
Coyoacán                Entire home/apt     1706.249300
                        Hotel room          6806.000000
                        Private room         768.011461
                        Shared room          606.500000
Cuajimalpa de Morelos   Entire home/apt     2349.114286
                        Private room        1682.875000
Cuauhtémoc              Entire home/apt     2134.103544
                        Hotel room         58952.902439
                        Private room        1375.176598
                        Shared room          344.460227
Gustavo A. Madero       Entire home/apt     1009.534247
                        Private room         682.946429
                        Shared room          184.625000
Iztacalco               Entire home/apt     1105.252000
                        Private room         691.659574
                        Shared room         1288.333333
Iztapalapa              Entire home/apt      750.724832
                        Private room         759.207207
                        Shared room          402.000000
La Magdalena Contreras  Entire home/apt     1400.254545
                        Private room         982.150943
Miguel Hidalgo          Entire home/apt     2180.229831
                        Hotel room          1097.416667
                        Private room        1008.548067
                        Shared room          458.875000
Milpa Alta              Entire home/apt     1873.000000
                        Private room         450.428571
Tlalpan                 Entire home/apt     1522.045455
                        Private room        3310.602941
                        Shared room                 NaN
Tláhuac                 Entire home/apt      481.000000
                        Private room         305.133333
Venustiano Carranza     Entire home/apt     1042.366316
                        Private room         575.390244
                        Shared room          468.000000
Xochimilco              Entire home/apt     1497.464789
                        Private room         558.734694
Álvaro Obregón          Entire home/apt     1502.182203
                        Hotel room          1631.000000
                        Private room        2992.357143
                        Shared room          267.000000
Name: precio, dtype: float64

In [ ]:
df_copia.columns

Index(['id', 'nombre', 'id_anfitrion', 'nombre_anfitrion', 'colonia',
       'latitud', 'longitud', 'tipo_habitacion', 'precio', 'noches_minimas',
       'numero_resenas', 'ultima_resena', 'resenas_por_mes',
       'propiedades_anfitrion', 'disponibilidad_365', 'number_of_reviews_ltm'],
      dtype='object')

In [ ]:
# Entender si number_of_reviews influye en el precio del alojamiento
#number_of_reviews_ltm
df_copia.groupby("number_of_reviews_ltm")["precio"].mean().sort_values(ascending = False)

number_of_reviews_ltm
0      3220.883633
192    2530.000000
153    2427.500000
156    2220.000000
366    2210.000000
          ...
109     632.333333
178     621.000000
117     589.166667
170     462.000000
147            NaN
Name: precio, Length: 191, dtype: float64

In [ ]:
df_copia.groupby("colonia")["number_of_reviews_ltm"].mean().sort_values(ascending = False)

colonia
Venustiano Carranza       23.228225
Cuauhtémoc                18.583506
Azcapotzalco              17.891473
Iztacalco                 17.775934
Miguel Hidalgo            14.325388
Gustavo A. Madero         14.225243
Benito Juárez             12.550049
Coyoacán                  11.775333
Cuajimalpa de Morelos     11.151220
Iztapalapa                10.672185
Álvaro Obregón             8.369121
Tlalpan                    7.038462
Xochimilco                 5.780645
La Magdalena Contreras     4.586957
Milpa Alta                 3.800000
Tláhuac                    3.350000
Name: number_of_reviews_ltm, dtype: float64

In [ ]:
 df_copia.groupby("colonia")["disponibilidad_365"].mean().sort_values(ascending = False)

colonia
Milpa Alta                282.700000
Xochimilco                275.741935
Tláhuac                   272.875000
Iztapalapa                264.135762
Gustavo A. Madero         257.376699
Cuajimalpa de Morelos     245.034146
Azcapotzalco              242.801034
Álvaro Obregón            237.968303
Iztacalco                 234.263485
Miguel Hidalgo            234.240761
Cuauhtémoc                232.449177
Venustiano Carranza       229.916207
Benito Juárez             228.702948
Tlalpan                   227.830025
Coyoacán                  216.537348
La Magdalena Contreras    200.615942
Name: disponibilidad_365, dtype: float64

In [ ]:
df_copia["precio"]

0         3673.0
1        18000.0
2          591.0
3            NaN
4            NaN
          ...
27046     1096.0
27047      260.0
27048      996.0
27049      458.0
27050     3082.0
Name: precio, Length: 27051, dtype: float64

In [ ]:
#Manejo de Nan de la columna precio
filtro = df_copia['precio'].isna()
filtro

0        False
1        False
2        False
3         True
4         True
         ...
27046    False
27047    False
27048    False
27049    False
27050    False
Name: precio, Length: 27051, dtype: bool

In [ ]:
df_nan_precio = df_copia[filtro]
df_nan_precio

,id,nombre,id_anfitrion,nombre_anfitrion,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,Coyoacán,19.354480,-99.162170,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8
5,131610,MARIA DEL ALMA,647454,Fernando,Coyoacán,19.354160,-99.164880,Private room,NaN,1,0,NaT,NaN,3,0,0
9,187030,Spacious apt with the best rooftop in Condesa,899360,Julian,Cuauhtémoc,19.410570,-99.177300,Entire home/apt,NaN,4,103,2023-09-08,0.61,6,0,0
10,187745,Extraordinarily Spacious Apt. in Condesa,899360,Julian,Cuauhtémoc,19.410570,-99.177300,Entire home/apt,NaN,14,24,2018-01-03,0.17,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26375,1492790535447381248,3 High-End Apts with Private Rooftop @ Roma Norte,114564195,Fernando,Cuauhtémoc,19.420714,-99.165345,Entire home/apt,NaN,1,0,NaT,NaN,28,51,0
26399,1493527488230562415,Muy práctico y bonito,714991006,Claudia,Benito Juárez,19.384030,-99.137250,Entire home/apt,NaN,1,2,2025-09-05,2.00,1,267,2
26421,1494433329501631014,Habitación Plaza de toros México,385040544,Francisco,Benito Juárez,19.382454,-99.184501,Private room,NaN,1,0,NaT,NaN,1,364,0
26452,1495750044495995126,Espacio ejecutivo en el centro,23021265,Jesy,Cuauhtémoc,19.429344,-99.158556,Entire home/apt,NaN,1,1,2025-08-29,1.00,27,326,1
26512,1497284964842221388,Mexico City Chill Spot,694845089,Carlos,Miguel Hidalgo,19.431671,-99.174365,Entire home/apt,NaN,2,0,NaT,NaN,1,138,0

In [ ]:
# Cuantos valores nan en precio se tiene por colonia
df_nan_precio.groupby("colonia").count()

,id,nombre,id_anfitrion,nombre_anfitrion,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
colonia,,,,,,,,,,,,,,,
Azcapotzalco,43,43,43,43,43,43,43,0,43,43,31,31,43,43,43
Benito Juárez,559,559,559,558,559,559,559,0,559,559,416,416,559,559,559
Coyoacán,312,312,312,311,312,312,312,0,312,312,220,220,312,312,312
Cuajimalpa de Morelos,61,61,61,61,61,61,61,0,61,61,38,38,61,61,61
Cuauhtémoc,1261,1261,1261,1261,1261,1261,1261,0,1261,1261,1043,1043,1261,1261,1261
Gustavo A. Madero,56,56,56,56,56,56,56,0,56,56,34,34,56,56,56
Iztacalco,41,41,41,41,41,41,41,0,41,41,32,32,41,41,41
Iztapalapa,41,41,41,41,41,41,41,0,41,41,16,16,41,41,41
La Magdalena Contreras,30,30,30,30,30,30,30,0,30,30,16,16,30,30,30
Miguel Hidalgo,594,594,594,594,594,594,594,0,594,594,453,453,594,594,594
Milpa Alta,8,8,8,8,8,8,8,0,8,8,3,3,8,8,8
Tlalpan,180,180,180,180,180,180,180,0,180,180,121,121,180,180,180
Tláhuac,6,6,6,6,6,6,6,0,6,6,1,1,6,6,6
Venustiano Carranza,91,91,91,91,91,91,91,0,91,91,78,78,91,91,91
Xochimilco,35,35,35,35,35,35,35,0,35,35,21,21,35,35,35
Álvaro Obregón,166,166,166,164,166,166,166,0,166,166,101,101,166,166,166

In [ ]:
df_nan_precio["colonia"].value_counts(normalize =  True)

colonia
Cuauhtémoc                0.361940
Miguel Hidalgo            0.170494
Benito Juárez             0.160448
Coyoacán                  0.089552
Tlalpan                   0.051665
Álvaro Obregón            0.047646
Venustiano Carranza       0.026119
Cuajimalpa de Morelos     0.017509
Gustavo A. Madero         0.016073
Azcapotzalco              0.012342
Iztapalapa                0.011768
Iztacalco                 0.011768
Xochimilco                0.010046
La Magdalena Contreras    0.008611
Milpa Alta                0.002296
Tláhuac                   0.001722
Name: proportion, dtype: float64

In [ ]:
## Imputación de valor nan en la columna precio

In [ ]:
# Remplazo por promedio,promedio,  moda, mediana, (tomando en cuenta todos los precios del dataset)
# Remplazo por promedio,promedio, moda, mediana, pero por colonia
# Remplazo por promedio, media, moda  pero por colonia y tipo de propiedad  (Imputar primero los valores del tipo de propiedad)
# Remplazo por promedio,promedio, moda, mediana, de acuerdo al tipo de propiedad

#Promedio suaviza el precio,

In [ ]:
# El precio para el alojamiento de casas grandes NO es el mismo en cada colonia
df_copia.groupby("tipo_habitacion")["precio"].mean().sort_values(ascending = False)

tipo_habitacion
Hotel room         42841.000000
Entire home/apt     1930.279504
Private room        1226.560462
Shared room          360.885827
Name: precio, dtype: float64

In [ ]:
## Valores atípicos en precio

In [ ]:
df_copia["precio"].min()

61.0

In [ ]:
df_copia["precio"].max()

900000.0

In [ ]:
#Registro con el precio mas alto
filtro =  df_copia['precio'] == 900000
df_copia[filtro]

,id,nombre,id_anfitrion,nombre_anfitrion,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
14503,892676742760732948,¡Recámara acogedora y muy cómoda!,270168697,Evan,Tlalpan,19.28152,-99.15623,Private room,900000.0,1,3,2024-09-29,0.13,1,364,1

In [ ]:
#Registro con el precio mas bajo
filtro =  df_copia['precio'] == 61
df_copia[filtro]

,id,nombre,id_anfitrion,nombre_anfitrion,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
22296,1327580316106887410,JC Friends Roma,244230249,Joel Genaro,Cuauhtémoc,19.40455,-99.16268,Shared room,61.0,1,4,2025-06-01,0.62,9,73,4

In [ ]:
q = df_copia["precio"].quantile(0.99)

In [ ]:
df_copia[df_copia["precio"] < q]

,id,nombre,id_anfitrion,nombre_anfitrion,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm
0,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3673.0,1,0,NaT,NaN,1,363,0
2,56074,Great space in historical San Rafael,265650,Maris,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1
6,165772,BEST 5 Bedroom HOUSE IN S. Miguel Chapultepec,790208,Francisco Carlos,Miguel Hidalgo,19.408260,-99.186590,Entire home/apt,3673.0,2,386,2025-08-10,2.24,5,201,28
7,171109,Cool room near WTC and Metrobus,816295,Carlos,Benito Juárez,19.396750,-99.175810,Private room,321.0,4,123,2025-09-07,0.88,2,301,15
8,180808,"Huge Luxurious Suite 70's style, perfectly loc...",36836,Roberto,Cuauhtémoc,19.423900,-99.168900,Entire home/apt,1190.0,3,62,2025-09-01,0.38,1,315,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27046,1518356968266486778,Suite Frida,674644167,Heyliana,Venustiano Carranza,19.442240,-99.113440,Private room,1096.0,1,0,NaT,NaN,5,365,0
27047,1518388105556721163,Habitación a un costado de Ciudad Universitaria,222854336,Marco Antonio,Coyoacán,19.308017,-99.168158,Private room,260.0,1,0,NaT,NaN,1,365,0
27048,1518433354720281854,Espacioso departamento en Anzures,470800231,Hector Fernando,Miguel Hidalgo,19.434460,-99.174010,Entire home/apt,996.0,1,0,NaT,NaN,20,365,0
27049,1518462568893975567,Casa Roma Baja 05,710857718,Camila,Cuauhtémoc,19.406435,-99.160934,Entire home/apt,458.0,1,0,NaT,NaN,7,363,0
27050,1518561444972990747,Departamento con Terraza privada Roma Norte,362149590,Ilse,Cuauhtémoc,19.413682,-99.154815,Entire home/apt,3082.0,1,0,NaT,NaN,4,365,0

## Imputación de la columna precio
Se usa el promedio por que suaviza los precios,
Desicion: Remplazo por promedio por colonia y tipo de propiedad para tener un precio más acorde a la ubicación, ya que como se analizo este depende de la colonia y de tipo de propiedad.

In [ ]:
df_copia["precio_agregado"] = df_copia["precio"]
df_precios = df_copia.groupby("colonia")["precio"].mean()
df_precios

colonia
Azcapotzalco               708.098837
Benito Juárez             1120.261867
Coyoacán                  1245.479152
Cuajimalpa de Morelos     2150.578797
Cuauhtémoc                2126.383364
Gustavo A. Madero          821.398693
Iztacalco                  930.181406
Iztapalapa                 752.996169
La Magdalena Contreras    1195.074074
Miguel Hidalgo            1876.386781
Milpa Alta                1420.363636
Tlalpan                   2493.466454
Tláhuac                    403.411765
Venustiano Carranza        845.509804
Xochimilco                1114.150000
Álvaro Obregón            2117.761084
Name: precio, dtype: float64

In [ ]:
## Diccionario con promedios por cada colonoa --> Python
## Groupby

df_copia["precio_agregado"] = np.where(df_copia["precio_agregado"].isna(), df_copia["colonia"].map(df_precios), df_copia["precio_agregado"])

In [ ]:

df_copia["precio_agregado"]

0         3673.000000
1        18000.000000
2          591.000000
3         2126.383364
4         1245.479152
             ...
27046     1096.000000
27047      260.000000
27048      996.000000
27049      458.000000
27050     3082.000000
Name: precio_agregado, Length: 27051, dtype: float64

In [ ]:

df_copia

,id,nombre,id_anfitrion,nombre_anfitrion,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,precio_agregado
0,35797,Villa Dante,153786,Dici,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3673.0,1,0,NaT,NaN,1,363,0,3673.000000
1,44616,Condesa Haus,196253,Fernando,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1,18000.000000
2,56074,Great space in historical San Rafael,265650,Maris,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1,591.000000
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1,2126.383364
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,Coyoacán,19.354480,-99.162170,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8,1245.479152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27046,1518356968266486778,Suite Frida,674644167,Heyliana,Venustiano Carranza,19.442240,-99.113440,Private room,1096.0,1,0,NaT,NaN,5,365,0,1096.000000
27047,1518388105556721163,Habitación a un costado de Ciudad Universitaria,222854336,Marco Antonio,Coyoacán,19.308017,-99.168158,Private room,260.0,1,0,NaT,NaN,1,365,0,260.000000
27048,1518433354720281854,Espacioso departamento en Anzures,470800231,Hector Fernando,Miguel Hidalgo,19.434460,-99.174010,Entire home/apt,996.0,1,0,NaT,NaN,20,365,0,996.000000
27049,1518462568893975567,Casa Roma Baja 05,710857718,Camila,Cuauhtémoc,19.406435,-99.160934,Entire home/apt,458.0,1,0,NaT,NaN,7,363,0,458.000000
27050,1518561444972990747,Departamento con Terraza privada Roma Norte,362149590,Ilse,Cuauhtémoc,19.413682,-99.154815,Entire home/apt,3082.0,1,0,NaT,NaN,4,365,0,3082.000000

In [ ]:
df_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27051 entries, 0 to 27050
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     27051 non-null  int64
 1   nombre                 27051 non-null  object
 2   id_anfitrion           27051 non-null  int64
 3   nombre_anfitrion       27045 non-null  object
 4   colonia                27051 non-null  object
 5   latitud                27051 non-null  float64
 6   longitud               27051 non-null  float64
 7   tipo_habitacion        27051 non-null  object
 8   precio                 23567 non-null  float64
 9   noches_minimas         27051 non-null  int64
 10  numero_resenas         27051 non-null  int64
 11  ultima_resena          23650 non-null  datetime64[ns]
 12  resenas_por_mes        23650 non-null  float64
 13  propiedades_anfitrion  27051 non-null  int64
 14  disponibilidad_365     27051 non-null  int64
 15  number_of_reviews_ltm  27051 non-null  int64
 16  precio_agregado        27051 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(7), object(4)
memory usage: 3.5+ MB

In [ ]:
df_copia.groupby(['colonia','tipo_habitacion'])['precio'].mean()

colonia                 tipo_habitacion
Azcapotzalco            Entire home/apt      863.431280
                        Private room         461.669173
Benito Juárez           Entire home/apt     1444.690254
                        Hotel room                  NaN
                        Private room         657.923695
                        Shared room          370.117647
Coyoacán                Entire home/apt     1706.249300
                        Hotel room          6806.000000
                        Private room         768.011461
                        Shared room          606.500000
Cuajimalpa de Morelos   Entire home/apt     2349.114286
                        Private room        1682.875000
Cuauhtémoc              Entire home/apt     2134.103544
                        Hotel room         58952.902439
                        Private room        1375.176598
                        Shared room          344.460227
Gustavo A. Madero       Entire home/apt     1009.534247
                        Private room         682.946429
                        Shared room          184.625000
Iztacalco               Entire home/apt     1105.252000
                        Private room         691.659574
                        Shared room         1288.333333
Iztapalapa              Entire home/apt      750.724832
                        Private room         759.207207
                        Shared room          402.000000
La Magdalena Contreras  Entire home/apt     1400.254545
                        Private room         982.150943
Miguel Hidalgo          Entire home/apt     2180.229831
                        Hotel room          1097.416667
                        Private room        1008.548067
                        Shared room          458.875000
Milpa Alta              Entire home/apt     1873.000000
                        Private room         450.428571
Tlalpan                 Entire home/apt     1522.045455
                        Private room        3310.602941
                        Shared room                 NaN
Tláhuac                 Entire home/apt      481.000000
                        Private room         305.133333
Venustiano Carranza     Entire home/apt     1042.366316
                        Private room         575.390244
                        Shared room          468.000000
Xochimilco              Entire home/apt     1497.464789
                        Private room         558.734694
Álvaro Obregón          Entire home/apt     1502.182203
                        Hotel room          1631.000000
                        Private room        2992.357143
                        Shared room          267.000000
Name: precio, dtype: float64

In [ ]:
df_copia.groupby(['colonia','tipo_habitacion'])['precio_agregado'].mean()

colonia                 tipo_habitacion
Azcapotzalco            Entire home/apt      851.849475
                        Private room         501.965848
Benito Juárez           Entire home/apt     1389.958717
                        Hotel room          1120.261867
                        Private room         750.391329
                        Shared room          391.550339
Coyoacán                Entire home/apt     1654.670552
                        Hotel room          2635.609364
                        Private room         882.041368
                        Shared room          606.500000
Cuajimalpa de Morelos   Entire home/apt     2320.652904
                        Private room        1758.311096
Cuauhtémoc              Entire home/apt     2133.456702
                        Hotel room         45272.444143
                        Private room        1488.318476
                        Shared room          354.527590
Gustavo A. Madero       Entire home/apt      996.725017
                        Private room         703.924044
                        Shared room          184.625000
Iztacalco               Entire home/apt     1091.685644
                        Private room         714.594366
                        Shared room         1288.333333
Iztapalapa              Entire home/apt      750.907100
                        Private room         757.956063
                        Shared room          402.000000
La Magdalena Contreras  Entire home/apt     1380.072860
                        Private room        1048.516595
Miguel Hidalgo          Entire home/apt     2146.611983
                        Hotel room          1292.159195
                        Private room        1165.632510
                        Shared room          458.875000
Milpa Alta              Entire home/apt     1797.560606
                        Private room         854.568182
Tlalpan                 Entire home/apt     1669.055754
                        Private room        3087.112620
                        Shared room         2493.466454
Tláhuac                 Entire home/apt      473.610644
                        Private room         325.823529
Venustiano Carranza     Entire home/apt     1020.944782
                        Private room         600.082614
                        Shared room          468.000000
Xochimilco              Entire home/apt     1438.142262
                        Private room         730.835211
Álvaro Obregón          Entire home/apt     1570.579857
                        Hotel room          1909.149191
                        Private room        2787.155790
                        Shared room          267.000000
Name: precio_agregado, dtype: float64

In [ ]:
#Imputación considerando colonia y tipo de habitación
df_precios_col_hab = df_copia.groupby(["colonia","tipo_habitacion"])["precio"].mean()
df_precios_col_hab

colonia                 tipo_habitacion
Azcapotzalco            Entire home/apt      863.431280
                        Private room         461.669173
Benito Juárez           Entire home/apt     1444.690254
                        Hotel room                  NaN
                        Private room         657.923695
                        Shared room          370.117647
Coyoacán                Entire home/apt     1706.249300
                        Hotel room          6806.000000
                        Private room         768.011461
                        Shared room          606.500000
Cuajimalpa de Morelos   Entire home/apt     2349.114286
                        Private room        1682.875000
Cuauhtémoc              Entire home/apt     2134.103544
                        Hotel room         58952.902439
                        Private room        1375.176598
                        Shared room          344.460227
Gustavo A. Madero       Entire home/apt     1009.534247
                        Private room         682.946429
                        Shared room          184.625000
Iztacalco               Entire home/apt     1105.252000
                        Private room         691.659574
                        Shared room         1288.333333
Iztapalapa              Entire home/apt      750.724832
                        Private room         759.207207
                        Shared room          402.000000
La Magdalena Contreras  Entire home/apt     1400.254545
                        Private room         982.150943
Miguel Hidalgo          Entire home/apt     2180.229831
                        Hotel room          1097.416667
                        Private room        1008.548067
                        Shared room          458.875000
Milpa Alta              Entire home/apt     1873.000000
                        Private room         450.428571
Tlalpan                 Entire home/apt     1522.045455
                        Private room        3310.602941
                        Shared room                 NaN
Tláhuac                 Entire home/apt      481.000000
                        Private room         305.133333
Venustiano Carranza     Entire home/apt     1042.366316
                        Private room         575.390244
                        Shared room          468.000000
Xochimilco              Entire home/apt     1497.464789
                        Private room         558.734694
Álvaro Obregón          Entire home/apt     1502.182203
                        Hotel room          1631.000000
                        Private room        2992.357143
                        Shared room          267.000000
Name: precio, dtype: float64

In [ ]:
filtro = df_precios_col_hab.isna()
df_habitacion_nan = df_precios_col_hab[filtro]
df_habitacion_nan

colonia        tipo_habitacion
Benito Juárez  Hotel room        NaN
Tlalpan        Shared room       NaN
Name: precio, dtype: float64

In [ ]:
#df_copia["precio_agregado2"] = df_copia["precio"]

In [ ]:
promedio_general = df_copia.groupby("colonia")["precio"].mean()
promedio_general
filtro1 = ~df_copia["precio"].isna()
df1 = df_copia[filtro1]
df1

filtro1 = (df1["colonia"] == "Benito Juárez") & (df1["tipo_habitacion"] == "Hotel room" )
df1[filtro1]

#print("Promedio: ", promedio)

#df_valores = df_copia[filtro1]
#df_valores

#filtro2 = (df_valores["colonia"] == "Benito Juárez") & (df_valores["tipo_habitacion"] == "Hotel room")


#print("Promedio para Benito Juárez: ", promedio)

#print(promedio_benito_juarez)
#df_copia["precio_agregado2"] = np.where( (df_copia["colonia"]=="Benito Juárez" & df_copia["tipo_habitacion"] == "Hotel room") , )

#mean(skipna=True)

Empty DataFrame
Columns: [id, nombre, id_anfitrion, nombre_anfitrion, colonia, latitud, longitud, tipo_habitacion, precio, noches_minimas, numero_resenas, ultima_resena, resenas_por_mes, propiedades_anfitrion, disponibilidad_365, number_of_reviews_ltm, precio_agregado]
Index: []